### ISSUE TITLE
FPS cut in half with using vsync

### ISSUE THREAD

**Issue by LiEyWe** [cam72cam/ImmersiveRailroading#100]
As the title says, with vsync and immersive railroading installed, the fps go from 60 to 30.
Without vsync, it drops about 10 fps from about 80 to 70

**Comment by cam72cam** [comment]
I am having trouble reproducing, what GFX card do you have?

**Comment by LiEyWe** [comment]
R9 200 Series.
R9 280x specifically.
My brother has a GTX 960 and he has the same problems with vsync.

**Comment by cam72cam** [comment]
I should drop in my R9380 and give it a test

**Comment by BrisingrAerowing** [comment]
I'm noticing the same on the temporary system I am using (as my main system is in for repairs [bad power socket]). This one has Intel HD Integrated Graphics.

**Comment by cam72cam** [comment]
I've improved the rendering system significantly over the past few updates.  I am going to close this for now, feel free to re-open if you are still experiencing the issue
