### ISSUE TITLE
Items Invisible in JEI

### ISSUE THREAD

**Issue by Darkosto** [cam72cam/ImmersiveRailroading#104]
Hello,

I loaded up IR on a 1.12.1 custom pack and the items are not showing up in JEI at all:

https://i.artdude.uk/darkosto/w6gzUQS2.mp4

MC: 1.12.1
Forge: 2485
IR: 0.3.2

Thanks for your help!
Darkosto

**Comment by b0bst3r** [comment]
I just had this but the items flash on and off like somethings stopping them showing.

jei_1.12.2-4.7.11.101
ImmersiveRailroading-0.3.2
JEI Integration-1.12.1-1.4.2.31

**Comment by cam72cam** [comment]
Turns out JEI has a way to mark items as "don't mess with the rendering".  I do all sorts of magical hyginks to render my items quickly which break jei's own render optimizations.

**Comment by Darkosto** [comment]
Thank you very much for looking into this! I look forward to playing with the mod some more :)
