### ISSUE TITLE
Crash when trying to load coal blocks into item.immersiverailroading:item_rolling_stock.rolling_stock/locomotives/a1_peppercorn.json.name

### ISSUE THREAD

**Issue by RiftomeR** [cam72cam/ImmersiveRailroading#111]
[crash-2017-10-19_11.48.59-client.txt](https://github.com/cam72cam/ImmersiveRailroading/files/1397539/crash-2017-10-19_11.48.59-client.txt)

**Comment by cam72cam** [comment]
Dupe of https://github.com/cam72cam/ImmersiveRailroading/issues/67

**Comment by cam72cam** [comment]
You can't shift click on an empty slot or double click on it

**Comment by cam72cam** [comment]
Crash is fixed
