### ISSUE TITLE
Recipes not using dictionary.

### ISSUE THREAD

**Issue by madhatr** [cam72cam/ImmersiveRailroading#112]
Not sure how to label it, I only know of the ore dictionary.

While crafting the steam hammer I noticed it can only be crafted with immersive steel and not steel from other mods.

Will this be changed in the future or an option added to allow use of other mod material?

**Comment by cam72cam** [comment]
The recipe will be going away and be replaced with making a immersive engineering style multiblock

**Comment by madhatr** [comment]
Nice, will that multi-block accept steel from other mods?

**Comment by cam72cam** [comment]
Will be fixed by #157
