### ISSUE TITLE
FPS drops by 3/4 when looking at rail parts in JEI

### ISSUE THREAD

**Issue by madhatr** [cam72cam/ImmersiveRailroading#114]
FPS goes from 60 solid, down to 12-13 while observing parts in JEI

GTX 1080ti Hybrid
i7 7700K

**Comment by cam72cam** [comment]
Which version of the mod?

**Comment by madhatr** [comment]
Sorry I never replied.  I now forget which version it was but the issue is gone now in current versions.

**Comment by cam72cam** [comment]
Awesome, sounds like my GPU optimizations helped!
