### ISSUE TITLE
US Tanker car front wheels rotate along the wrong axis

### ISSUE THREAD

**Issue by jjenco** [cam72cam/ImmersiveRailroading#126]
Not sure if I'm describing that quite correctly in the title, so I took a quick video. Basically, the front wheels of the tanker car rotate as a pair along an invisible axis that's in between the wheels, whereas the rear wheels behave correctly. 

https://drive.google.com/open?id=1U_ofIVhzrrAOW4OYTD0lD8fa4-HsHcYm

**Comment by cam72cam** [comment]
hah, that's a good one.  I'll fix that tonight
