### ISSUE TITLE
Fix Curse setup

### ISSUE THREAD

**Issue by josephcsible** [cam72cam/ImmersiveRailroading#132]
A few issues I noticed with this mod's Curse setup:
1. TrackAPI and Immersive Engineering should be marked as required dependencies, so they're automatically downloaded with this mod
2. Links to "Issues" and "Source" should be added pointing to this issue tracker and main source page, rather than just sticking a link in the mod's description

**Comment by cam72cam** [comment]
2: is done, I'll have to figure out how to do 1

**Comment by josephcsible** [comment]
Dependencies are set on the page where you upload files. You can set them on existing files too by editing them.

**Comment by cam72cam** [comment]
Done
