### ISSUE TITLE
Remove hard dependency on Immersive Engineering

### ISSUE THREAD

**Issue by josephcsible** [cam72cam/ImmersiveRailroading#133]
After [IE's licensing debacle](https://github.com/BluSunrize/ImmersiveEngineering/pull/2543#issuecomment-339201673), some people (myself included) have tried to stay away from it. Is there a chance that the hard dependency on it could be removed, and alternative ways added for whatever it provides?

**Comment by cam72cam** [comment]
That's a fair point.  I saw a little bit of chatter, but did not realize Blu went forward without getting contributor signoff.  I was planning on depending on some of their code, but that won't happen now.

Thanks for the heads up.  I'll have this resolved by the next release

**Comment by cam72cam** [comment]
Needs:
* Fix crash on load
* Ore-dict treated wood
