### ISSUE TITLE
Trains dupe-dropping into donuts of doom

### ISSUE THREAD

**Issue by Nachtflame** [cam72cam/ImmersiveRailroading#136]
So, I posted a pic about this about a week ago, where a boxcar had suffered this fate to the point of horrific entity lag. I've had it happen again, this time with the front of the train.  The common factor seems to be that in both cases, the trains in question were left straddling 2 track sections during world restarts.

**Comment by cam72cam** [comment]
I'll try my best to reproduce this and fix it before the next release
