### ISSUE TITLE
[Suggestion] Make more angles for straight track.

### ISSUE THREAD

**Issue by Dushess** [cam72cam/ImmersiveRailroading#142]
Of course it needs any curves to have similar adaptations. Just because by realistic state of this mod better have more "free" railways directions.

**Comment by Dushess** [comment]
I will even say about valculated curve shape, but you choosed other type. And it even it have own pros.

**Comment by cam72cam** [comment]
The track API will allow us to use https://github.com/DonBruce64/OpenFlexiTrack when it is released in a few months.
