### ISSUE TITLE
The switch is incorrect

### ISSUE THREAD

**Issue by Dushess** [cam72cam/ImmersiveRailroading#143]
It have only one section working, should be both. 
![2017-12-10_14 31 53](https://user-images.githubusercontent.com/15954961/33804531-06246398-ddb8-11e7-8487-a4e0e2b498ec.png)
![2017-12-10_14 31 58](https://user-images.githubusercontent.com/15954961/33804532-064710d2-ddb8-11e7-98b4-136e3784f72a.png)
And if you use ready model for each angle, need to create place for wheels at inner rails crossing point. 
[this thing](https://www.joc.com/sites/default/files/field_feature_image/rail-switch-shutterstock_90593281-600.jpg)

Upd. Smooth mode doesn't work for switch continue, if quarters=1.

I placed rails perfectly to 2nd way, but this happened. 
![2017-12-10_14 45 08](https://user-images.githubusercontent.com/15954961/33804592-484ddf1e-ddb9-11e7-9af4-332b5f301c62.png)

**Comment by cam72cam** [comment]
Placement on switches is a little funky.  Does it work if you place the locomotive on a straight and then drive it onto the switch?

**Comment by Dushess** [comment]
Actually i did this, it just can go straight or on 2nd way, if it have also 90deg placement.

**Comment by cam72cam** [comment]
So to confirm, this only happens when the train is placed directly on the switch?

**Comment by Dushess** [comment]
This happens, when train, placed normally, reached the switch.

**Comment by cam72cam** [comment]
Ok, I was able to reproduce the issue.  A temporary solution is to make the radius of the track larger.  When the switch has a small radius the movement code can get confused.

**Comment by cam72cam** [comment]
Thanks for the bug report, I'll try to get it fixed for the release I have planned for next weekend
