### ISSUE TITLE
Tesselating Block In World

### ISSUE THREAD

**Issue by kreezxil** [cam72cam/ImmersiveRailroading#151]
Have the version 0.3.9 which gave one my players an NPE and Tesselating Block in World message. Prior to the crash it kept saying he was missing 3 ties and he was testing the mod in creative.

client crash report
https://pastebin.com/GnkiVe2d

**Comment by cam72cam** [comment]
There's probably a mod conflict causing this.  I'll add a try/catch around here soon

**Comment by cam72cam** [comment]
Fixed the crash in 0.4.2
