### ISSUE TITLE
0.3.9 Clipping and coloring.

### ISSUE THREAD

**Issue by kreezxil** [cam72cam/ImmersiveRailroading#152]
Rail stock (engines, box cars, etc) appear to flicker as you walk around them. The ones that allow you to walk on their roofs vanish when looking down at them making it seem as if you are in fly mode.

The models have turned to a brownish to red-brownish hue, no longer matching the icons in the JEI.

[![Video Proof](https://img.youtube.com/vi/iD_Cy2A763k/0.jpg)](https://www.youtube.com/watch?v=iD_Cy2A763k)

**Comment by cam72cam** [comment]
Should be fixed
