### ISSUE TITLE
Track Suggestions

### ISSUE THREAD

**Issue by cam72cam** [cam72cam/ImmersiveRailroading#192]

**Comment by cam72cam** [comment]
RaptorTheRailfan:
![](https://cdn.discordapp.com/attachments/355731184157720579/404279812732092416/image.jpg)

**Comment by cam72cam** [comment]
X Switch from Lucky Ross

**Comment by cam72cam** [comment]
Pie_Coma:
Adjustable crossover

**Comment by cam72cam** [comment]
DoneFear: Y Switch
https://github.com/cam72cam/ImmersiveRailroading/issues/180

**Comment by cam72cam** [comment]
Would be nice to fix https://github.com/cam72cam/ImmersiveRailroading/issues/150 as part of this work

**Comment by Dushess** [comment]
Please don't forget about this crossing points, inner side.

**Comment by Railroadactive** [comment]
It would also be nice to have track bumpers, so even if the config is set to allow trains to destroy blocks, the trains would not run off the track and recreate "A close shave for duck" Some ideas would be like the Hayes style, [https://www.google.ca/url?sa=i&source=images&cd=&cad=rja&uact=8&ved=2ahUKEwjHpP-N_JXcAhWIl-AKHciUAgsQjRx6BAgBEAU&url=http%3A%2F%2Fmodel-railroad-hobbyist.com%2Fnode%2F5331&psig=AOvVaw3DNuq9Xxb8I1g3ge8S944f&ust=1531361454038415
](url)
or halfmoons 
[http://modeltraingeek.com/wp-content/uploads/2015/12/2015-12-14-04.25.33.jpg](url)

**Comment by km00700** [comment]
The track bumpers are already planned.
