### ISSUE TITLE
game mode/sub-mod missions to connect villages ala OpenTTD

### ISSUE THREAD

**Issue by SpudsMcCat** [cam72cam/ImmersiveRailroading#200]
sorta openTTD "village x: y: wants to be connected to village x1: y1: and is wiling to pay X emeralds
perhaps a seperate sub-mod for that ;/

**Comment by cam72cam** [comment]
I plan to experiment this week with a system which adds a whistle item to make vileagers board and disembark from train cars.  They would pay a certain number of emeralds for the distance traveled
