### ISSUE TITLE
add Bridge track types

### ISSUE THREAD

**Issue by SpudsMcCat** [cam72cam/ImmersiveRailroading#201]
Add ability to make different bridges around the rail as placed.
Trestle under track
beam (aka over road) [as a new block type that gets autoplaces by existing system?]
truss/cantaliever above track
etc.

**Comment by cam72cam** [comment]
Try using the Rail Bed Fill feature.  It will allow you to choose a block to put under the track automatically for making bridges and filling gaps.

Items can be added to the in game list by adding it to the "railBed" ore dictionary.  They must have a solid top face.

**Comment by cam72cam** [comment]
If that is insufficient, comment here and re-open the ticket

**Comment by SpudsMcCat** [comment]
I was thinking of 2 different modes. 1. for regular rail, a block added, to be used in rail bed, to make  it look like [http://ceephotos.karcor.com/wordpress/wp-content/uploads/20110323-amead-Railroad-Bridge-over-Seaway-Dr-Muskegon-MI.jpg](url)

for 2nd mode , having a straight+bridge track, that  adds truss, like [http://multimedia.scmp.com/news/china/article/One-Belt-One-Road/img/london/04_kazan_volga.jpg](url)
or places spans/arches and support columns under, like [http://www.lewisbogatyphotography.com/img/s/v-3/p2010895143-5.jpg](url)

**Comment by cam72cam** [comment]
I am not planning on adding those sorts of buildable structures. as part of track laying
Look at other mods like RFtools for copying a pre-built section multiple times
