### ISSUE TITLE
Idea: Signal System and/or Railway Control Methods

### ISSUE THREAD

**Issue by DorniNerd** [cam72cam/ImmersiveRailroading#206]
Perhaps something like the Railcraft or Signals mods (see below). Manual or automatic signalling to start and stop trains (Perhaps through use of redstone or bus/"data" cables through opencomputers or computercraft) for the purpose of building signal boxes like those attached. Am working working on using open computers to build and generate trains, stop and start trains, etc etc.

![image](https://user-images.githubusercontent.com/25697133/35773976-fbb5d3b2-092f-11e8-8112-f60d80c667db.png)
![image](https://user-images.githubusercontent.com/25697133/35773985-46937d12-0930-11e8-8632-8f971b7fdf6c.png)
![image](https://user-images.githubusercontent.com/25697133/35773990-5b4a5866-0930-11e8-809b-63cc8bb2230f.png)
![image](https://user-images.githubusercontent.com/25697133/35773996-9adccf2c-0930-11e8-8626-768418662326.png)

OpenComputers: https://minecraft.curseforge.com/projects/opencomputers
ComputerCraft: http://www.computercraft.info/
RailCraft: https://minecraft.curseforge.com/projects/railcraft
Signals: https://minecraft.curseforge.com/projects/signals

**Comment by Dushess** [comment]
ProjectRed will be released soon, i think, we can use his x16 bus.

**Comment by Cyprex** [comment]
IE redstone wire connectors already have 16 channels

**Comment by cam72cam** [comment]
OC Integration has been added
