### ISSUE TITLE
Server crash - CME at java.util.ArrayList$Itr.checkForComodificatio

### ISSUE THREAD

**Issue by ProsperCraft** [cam72cam/ImmersiveRailroading#208]
https://paste.fedoraproject.org/paste/jNwboscOHWE5lSNkJJdFnA

I don't know what the users were doing at the time, we just added the mod to the pack.

[2018-02-04-1.log.gz](https://github.com/cam72cam/ImmersiveRailroading/files/1693339/2018-02-04-1.log.gz)

**Comment by cam72cam** [comment]
One of your other mods has a thread which is messing with the world entity list.  This is the line:
```
world.getEntities(EntityCoupleableRollingStock.class, EntitySelectors.IS_ALIVE);
```

I am doing that inside of the world tick handler on the main thread.  Not sure what other mod has a thread spawned which is messing with that list.
