### ISSUE TITLE
Change wording of turn quarters

### ISSUE THREAD

**Issue by cam72cam** [cam72cam/ImmersiveRailroading#211]
Suspicious_Mango suggests using X degrees instead.

22.5 degree turn
45 degree turn
...

It makes a lot more sense

**Comment by dumboldoor** [comment]
I disagree, I like the freedom of the track placement, let's not turn this in the RoW. If you do decide to do this, then please consider putting more work into OFT.

**Comment by dumboldoor** [comment]
into RoW*

**Comment by cam72cam** [comment]
This is just a change of the label name, not a functionality change
