### ISSUE TITLE
Make switchess great again!

### ISSUE THREAD

**Issue by dumboldoor** [cam72cam/ImmersiveRailroading#215]
If possivle, it would be nice to have a feature that would allow you to control turn length and straight length separately.

Type: Switch
Railbed
Railbed fill
Quarters: 1-4
Turn length: 0-100
Straight length: 0-100
Track gauge: Brunel, Standard, Narrow, Minecraft, Model

As a side note, it would also be cool if we could have angled switches again, but it's fine if we don't.

**Comment by dumboldoor** [comment]
+Three way switches would be amazing too

**Comment by cam72cam** [comment]
Dupe of https://github.com/cam72cam/ImmersiveRailroading/issues/192 and https://github.com/cam72cam/ImmersiveRailroading/issues/99
