### ISSUE TITLE
More Localization Support For Trains Name

### ISSUE THREAD

**Issue by TartaricAcid** [cam72cam/ImmersiveRailroading#222]
Just like the picture show.

I found that I had to overwrite the JSON file to translate train's name.

![Imgur](https://i.imgur.com/yrdscww.png)

**Comment by cam72cam** [comment]
That's going to be tricky, but I'll see if I can provide a way to do that

**Comment by cam72cam** [comment]
You can now override the json names with `immersiverailroading:entity.type.name=override`
Ex:
```
immersiverailroading:entity.locomotives.emd_sd40-2=Super Magic Train
```

**Comment by TartaricAcid** [comment]
thanks
