### ISSUE TITLE
Server crash - CME

### ISSUE THREAD

**Issue by ProsperCraft** [cam72cam/ImmersiveRailroading#223]
https://paste.fedoraproject.org/paste/nClp0N8lnHN5m6BVXoX1pQ

**Comment by cam72cam** [comment]
All that line is doing is calling:
world.getEntities(EntityCoupleableRollingStock.class, ...)

It looks like some other mod is doing bad things go "world.loadedEntityList" in another thread

**Comment by ProsperCraft** [comment]
Please re-open, it happened again on a fresh server instance with no players running chunk pregen-

https://paste.fedoraproject.org/paste/8XbwPSuAKtEDUuEZ0qKNOQ

**Comment by cam72cam** [comment]
That is a different crash, but I'll re-open anyways

**Comment by cam72cam** [comment]
Ok that line is calling:
"List<EntityCoupleableRollingStock> entities = world.getEntities(EntityCoupleableRollingStock.class, EntitySelectors.IS_ALIVE);"

On the main thread in a tick handler.  Some other mod you have is messing with the loaded entity list in a different thread.
