### ISSUE TITLE
A fatal error occur at multiplay

### ISSUE THREAD

**Issue by gaojie429** [cam72cam/ImmersiveRailroading#230]
I found a issue and I confusing about this.
I`m playing Minecraft on multiplay  server with ImmersiveRailroading-mod. When I put the steam locomotive on the rail, other people can`t enter the server any longer until I remove it.
Fix this bug plz....

**Comment by cam72cam** [comment]
Can you send me their log files when they can't join?

**Comment by gaojie429** [comment]
OK, this is the log when they cant join.
(But I think you cant make out why this error has occurred from this log. If I misunderstand "log" means, please teach me.)
[00:57:48] [Server thread/INFO]: [USERNAME] joined the game
[00:57:49] [Server thread/INFO]:  [USERNAME] lost connection: TextComponent{text='Disconnected', siblings=[], style=Style{hasParent=false, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null}}
[00:57:49] [Server thread/INFO]:  [USERNAME]  left the game

**Comment by cam72cam** [comment]
I need their client logs, either fml-client-latest.log or latest.log

**Comment by cam72cam** [comment]
I honestly don't know what's breaking.  It looks like a weird conflict with another mod.  Is there a crash report from the clients?

**Comment by gaojie429** [comment]
No. Actually , I thought it is a weird conflict with another mod, so I put only ImmersiveEngineering, Railroading and TrackAPI on mods folder.

**Comment by cam72cam** [comment]
weird

**Comment by cam72cam** [comment]
I think this is fixed by the latest release, give it a try and let me know if it is still a problem
