### ISSUE TITLE
Locomotives and Rolling-stock become transparent when using shaderpacks.

### ISSUE THREAD

**Issue by AlexKnightPony** [cam72cam/ImmersiveRailroading#231]
Basically what the title says, I've tried Continuum, Seus and Sonic Ethers to name a few. The tracks look great and work fine with the shaderpacks, its possibly a problem with the settings for the shader mod or the way the stock are rendered. Anyways thanks for reading. 

In-game screenshot of the issue
![2018-03-02_16 09 25](https://user-images.githubusercontent.com/35781252/36924483-56087144-1e34-11e8-81d9-1edf9e2dbe03.png)

**Comment by gaojie429** [comment]
What shaderpack you use ?
Im using SEUS v.10.1 and that issue does not appear.

**Comment by AlexKnightPony** [comment]
im currently using SEUS 11.0 but it also happens with the latest version of continuum so im assuming its my settings

**Comment by mckenzieja** [comment]
Having the same issue as well with SEUS Renewed 1.0 and SEUS 11.0. Attempted to turn off as much as the advanced settings as allowed but nothing changed.

**Comment by AlexKnightPony** [comment]
So assuming it's just a problem with the latest version of SEUS, I'm guessing I could downgrade as a temporary fix.
