### ISSUE TITLE
Gameplay glucks

### ISSUE THREAD

**Issue by DFO28** [cam72cam/ImmersiveRailroading#233]
Mostly the mod works fine, but, unfourtunately, there are some issues that dont let to play easily. To start with, it's no idea how to control switches (rail type).  I looked lots of guides, they show the item called "detector", that makes switches working and changing railway for trains that are on it. It also uses redstone energy. But in my inventory I havent this item. Maybe, it was added on last versions of the mod, but here the second thing to come. 
Minecraft doesnt start working with newest versions, it says that modified version of the game is not supported. Memory of the game is set for 2035 MB. The highest version I can play with is 0.3.7, no idea why. 
Another interesting question on gameplay is taking trains out of the map (damaging it). For example, if I set the locomtive incorrectly, I want to wipe it out, or I dont need it anymore, I cant do that even by help of TNT. So, all installed trains are not able to remove.
Also sounds of train are not working, I cant give sound signal by Numpad as it said in instruction, other functions of locomotive work fine. (But its not as important as others glucks mentioned).
Finally, after  setting shaders to the game, trains are becoming transparent. I tried many versions of shaders, the best thing I achieved is that I can see trains when I am far away. When I come really close I cant see it. When I go onboard I still dont see the train, only its panel with level of breaks etc. It seems like my character just stays on the air, but physically its not an empty place, locomotive is working. 
I think those issues are simple to fix, but I dont know how. Advanced thanks for your help.

**Comment by Larky2k** [comment]
With Switches use redstone signals so use a leaver. Your very well behind on versions update to latest version and give MC more RAM. Locomotives/Rollingstock not properly on track move them and they be fine or shift left click remove from track. With shaders don't use them until the bug has been fixed.

**Comment by cam72cam** [comment]
Add foamfix and/or increase the memory given to the game.

Also you can try setting B:enableItemRenderPriming to false
