### ISSUE TITLE
Track Blueprint Placing Perpendicular

### ISSUE THREAD

**Issue by qwryzu** [cam72cam/ImmersiveRailroading#237]
Sometimes the track blueprint will randomly turn sideways in my inventory and then all blueprints that I place will be perpendicular to the direction that it would be expected to place. I've been trying to find info to see if this is an intentional mechanic that I just don't know how to use, but I've been using the latest 1.12.2 version since it came out a week or so and just started having this issue last night.
![2018-03-07_19 26 37](https://user-images.githubusercontent.com/27305244/37129834-fecfe7a0-223d-11e8-8969-04dd660aac3d.png)

A picture is attached to show the issue.

**Comment by cam72cam** [comment]
When this happens, does stair placement also go funny?

**Comment by cam72cam** [comment]
Cellman_XM8 found a case to reproduce it!

> I think I figured out the condition that causes the blueprint to rotate when going through snow. Whenever the side that snow gets plowed to changes, the blueprint will rotate.  In the first inventory slot you can see the blueprint rotate each time the side is swapped. https://gfycat.com/gifs/detail/ShallowLeafyBushsqueaker

**Comment by cam72cam** [comment]
```
EnumFacing[] horiz = EnumFacing.HORIZONTALS;
if (Math.random() > 0.5) {
    // Split between sides of the track
    ArrayUtils.reverse(horiz);
}
```

I might be an idiot

**Comment by qwryzu** [comment]
That would make perfect sense because I stopped noticing the issue right around when I got past the snowy mountains!
