### ISSUE TITLE
FTB revelations crash

### ISSUE THREAD

**Issue by cam72cam** [cam72cam/ImmersiveRailroading#241]
JimmyAllnighter reports that there is a memory leak when IR is combined with that pack

**Comment by cam72cam** [comment]
https://pastebin.com/gQC2XxSt

**Comment by JimmyAllnighter** [comment]
Just a note with that pastebin link: It will expire in 2 weeks. Here's one with a longer expiry in case it's needed: https://pastebin.com/SLRUxDDK
