### ISSUE TITLE
45 and 67.5 Switches Broken in Narrow Gauge

### ISSUE THREAD

**Issue by qwryzu** [cam72cam/ImmersiveRailroading#245]
Regardless of if the switch is flipped or not, trains will just go straight through narrow gauge switches that are 45 or 67.5 degrees - they don't turn onto the curved part. If a train comes from the curved part and tries to pass onto the straight track, the train will get stuck. 22.5 and 90 degree switches still work fine. 45 and 67.5 degree switches work fine in Standard and Minecraft gauge, I didn't test Brunel or Model.

**Comment by cam72cam** [comment]
What track lengths are you using?

**Comment by qwryzu** [comment]
15-35, none of which were working when I made the post but all of which all working now. I changed literally nothing about where I was placing the track, just went to a different part of the world and came back and it was working fine. I tried placing and replacing the track multiple times before and it still refused to work, no idea why it's working now.

**Comment by cam72cam** [comment]
very strange.  were you in smooth mode before and not now?

**Comment by qwryzu** [comment]
No I tried fixed and pixel, didn't check smooth though. If it happens again I'll try smooth.
