### ISSUE TITLE
add lite renderer mode 

### ISSUE THREAD

**Issue by gaojie429** [cam72cam/ImmersiveRailroading#246]
Please consider adding to config option that use lighter renderer to trains.
(like "enableItemRenderPriming" and "enableIconCache" option)

**Comment by cam72cam** [comment]
The loco and stock models are as light as they are going to get in code.  I've spent months optimizing the render pipeline.  If you are having performance issues, try disabling sounds or particles as they can eat into your CPU budge.  Also check that you have enough memory.

At some point in the future I may release a resource pack which disables the more GPU and CPU heavy models.

**Comment by gaojie429** [comment]
I didn't know that you spent a lot of time to be made loco suitable for low-spec PC...! I'm sorry.
Actually, my friend has some performance issues. I'll let him know that it is good for low-spec PC to turn off sounds and particles.

>>At some point in the future I may release a resource pack which disables the more GPU and CPU heavy models.
Thank you so much ! I'm looking forward to the day.
