### ISSUE TITLE
[1.12.2] Crash with Akashic Tome

### ISSUE THREAD

**Issue by MasterEnderman** [cam72cam/ImmersiveRailroading#250]
If you put the Immersive Railroading Manual in the Akashic Tome, use the Tome, select the Manual an look at a block the game crashes.

Forge: 14.23.2.2624
[Akashic Tome](https://minecraft.curseforge.com/projects/akashic-tome?gameCategorySlug=mc-mods&projectID=250577): 1.2.0-10
Immersive Engineering: 0.12-78
Track API: 1.1_1.12.2
Immersive Railroading: 0.5.3.1
Crash Report: https://pastebin.com/CWaR9ptg

**Comment by cam72cam** [comment]
You can get the fixed version here: http://174.138.127.16:8080/job/Immersive%20Railroading/11/

**Comment by MasterEnderman** [comment]
tried out the new version:
https://pastebin.com/4y8qiZmk
