### ISSUE TITLE
Resouce Leak

### ISSUE THREAD

**Issue by ichttt** [cam72cam/ImmersiveRailroading#252]
Hi, you are leaking some resources. Every IResource you get here: https://github.com/cam72cam/ImmersiveRailroading/blob/660c8aadc1ea61751271778434dd282b6251e79f/src/main/java/cam72cam/immersiverailroading/proxy/ClientProxy.java#L362 or https://github.com/cam72cam/ImmersiveRailroading/blob/660c8aadc1ea61751271778434dd282b6251e79f/src/main/java/cam72cam/immersiverailroading/proxy/ClientProxy.java#L367 needs to be closed in a try-with-resources or try-finally block

These leaks can be observed by forcing debug to be enabled for minecraft loggers using the log4j xml

**Comment by cam72cam** [comment]
Thanks for the heads up!
