### ISSUE TITLE
Disable Explosions Broken

### ISSUE THREAD

**Issue by qwryzu** [cam72cam/ImmersiveRailroading#253]
I have explosionsEnabled set to false, but a steam loco just blew up a big ol chunk of my rail yard. It's the new Big Boy that AdamRK just released so that could be an error on his end, I don't know if his work has control over that or if it's an error in the base mod.

**Comment by qwryzu** [comment]
And the K4 Pacific just exploded too. The MC mod menu still says it's set to false but just to be sure I'm going to change the config file directly, see if that does anything.

**Comment by cam72cam** [comment]
The in-game UI does not sync with the files on disk yet

**Comment by qwryzu** [comment]
That would explain that.

**Comment by cam72cam** [comment]
Can this ticket be closed?

**Comment by qwryzu** [comment]
Problem is solved for me but it might be a good reminder to eventually make the UI sync with the files on the disk. I'm not the dev tho, whatever works for you.
