### ISSUE TITLE
1.10.2 server crash interacting with casting

### ISSUE THREAD

**Issue by auddie2015** [cam72cam/ImmersiveRailroading#255]
When I right click the caster, the server shuts down.  I did it with a wrench and without with the same result.

I am not code savvy so I attached my crash report. It could be a mod conflict maybe. I certainly play with enough. (ImmersiveRailroading-0.5.3.1_1.10)

[crash-2018-03-21_21.09.22-client.txt](https://github.com/cam72cam/ImmersiveRailroading/files/1836652/crash-2018-03-21_21.09.22-client.txt)

**Comment by cam72cam** [comment]
This was reported in discord and fixed for the next release.  You can use the 1.10 dev build here for now:
http://174.138.127.16:8080/job/Immersive%20Railroading/31/

**Comment by auddie2015** [comment]
Awesome cam! Thanks!
