### ISSUE TITLE
Add Japanese trainsration.

### ISSUE THREAD

**Issue by gaojie429** [cam72cam/ImmersiveRailroading#260]
Hi, I saw you achieved complete translations on version 0.5.4. Since I am Japanese so I think it will be better if I can play this mod in Japanese. I made Japanese lang-file of this mod. Could you add this file to your mod ?
[ja_JP.zip](https://github.com/cam72cam/ImmersiveRailroading/files/1845150/ja_JP.zip)

**Comment by cam72cam** [comment]
Sure, I'll have this into the next release!

**Comment by cam72cam** [comment]
You can try it out here: http://174.138.127.16:8080/job/Immersive%20Railroading/81/

It will be published in the beta next week

**Comment by calloatti** [comment]
Somehow I read the title as "Add Japanese Train Station"

**Comment by gaojie429** [comment]
I have had mistake of spelling "translation". I typed "trainslation". Thats why you read as "Japanese train station" lol. Sorry (~_~;)
