### ISSUE TITLE
Rail placing line tool [Suggestion]

### ISSUE THREAD

**Issue by Ristelle** [cam72cam/ImmersiveRailroading#263]
What it says on the title.
With a line tool, you can place down points in the world. And then link them with the same tool by right clicking them. once done, you may place in the blueprint and it will build it for you.. provided you have enough materials.

Some notes:
- Line tool also needs to be able to adjust the turns of the track.

TLDR: A tool that is like your line tool in paint.net

**Comment by cam72cam** [comment]
This is how OpenFlexiTrack works and that mod will be compatible with IR once it's released (TrackAPI compat).  I'll be keeping my semi-static track as it is for now.
