### ISSUE TITLE
Add Rolling Stock Texture Selection Tool

### ISSUE THREAD

**Issue by WrongWeekend** [cam72cam/ImmersiveRailroading#270]
A newly built locomotive or car should have no color scheme beyond a generic gray/black combination and the colors naturally present in special metals, wood, glass, etc.

To add a paint scheme, players must use a paint can/bucket/brush/sprayer/etc. tool on the piece of rolling stock. Doing so brings up a list of schemes available for that specific piece as well as their respective dye costs (ideally with oredict support). Players can then choose one of the schemes, provided they have enough dyes, which consumes the dyes and applies the scheme to the locomotive or car. These dye costs should be configurable, or able to be eliminated entirely for creative play.

If a painted locomotive or car is disassembled, the paint scheme should be lost (mostly for simplicity's sake).

**Comment by NicholasRB** [comment]
Yeah having the scheme lost would also give us a reason not to take the car/loco off the tracks
