### ISSUE TITLE
the new rail rendering issue

### ISSUE THREAD

**Issue by gaojie429** [cam72cam/ImmersiveRailroading#271]
Hi! Thank you for adding Jpanese to your mod!!
Im enjoying v0.5.5 so much. But I found some rendering issue of rail. Our server set maximum loading chunk distance to 12, but of course some our member set it to less than 12 because of their machine power. However, though they set view-distance to 5, the rail that is put on out of their visible chunk is rendered!! They are suffering from this. Could you fix it ? Also, I found when I driving the train, sometimes rail and train blinks. (visible→transparent→visible. it happen within a second)
It is also good for me that fix this issue!

**Comment by cam72cam** [comment]
Give http://174.138.127.16:8080/job/Immersive%20Railroading/109/ a try in a few minutes when it finishes building.  It should fix the view distance issue.  I've seen the flickering a bit myself and need to figure out how to fix that

**Comment by gaojie429** [comment]
I put it on my server and finally fixed the view distance issue. Thank you !
It seems to the flickering started from v0.5.4. I think the new rail renderer may caused it.

**Comment by cam72cam** [comment]
Yeah, I need to figure out how to fix that
