### ISSUE TITLE
Running most up to date JAVA slow and glitchy running

### ISSUE THREAD

**Issue by gmavrick** [cam72cam/ImmersiveRailroading#273]
As the problem states when i run even the most recent version of the Immersive Railroading my game will run and freeze for a brief moment before resuming, then repeating. Even with the frame rate at set at unlimited or set ridiculously low (10). Please help. I am not sure what the issue is.

**Comment by ahbit** [comment]
How much Ram do you have allocated to the game?

**Comment by gmavrick** [comment]
I dont know, how would I check/change? and what do you recommend?

**Comment by gmavrick** [comment]
Nevermind, i upgraded the ram allocated ram. The game works wonderfully.
