### ISSUE TITLE
2 Suggestion

### ISSUE THREAD

**Issue by olegikoligik** [cam72cam/ImmersiveRailroading#275]
2 Suggestion:
- Icons instead of a projection of models (for disable freeze in inventory menu)
- Optional "locomotive control" (maybe gui). Because opencomputer is too difficult for usual players (most players).
P.S. Sorry if similar suggestion already are.

**Comment by cam72cam** [comment]
* B:enableIconCache=true in immersiverailroading_graphics.cfg
* You can do some basic stuff with redstone and the loco control augment.  Hit it with a redstone torch to change modes

**Comment by olegikoligik** [comment]
Wow, thanks for help!
