### ISSUE TITLE
T1 isnt satrting

### ISSUE THREAD

**Issue by LinaXHD** [cam72cam/ImmersiveRailroading#278]
so i have put coal and water in the T1 steam enginge locomotive every thing is working the steam comes out of the train BUT it wont drive when i press NUMPAD 8 i have allready checked the controlls of the mod and didnt now what to do the brake is off nothing could hold me but then there this specific problem
pleas help me im playing on the BETA version for 1.12.2

**Comment by ahbit** [comment]
Are you letting the engine build up to full steam before trying to move?
It will take a while before the steam is fully built up.

**Comment by LinaXHD** [comment]
thank you its worked

2018-03-31 15:25 GMT+02:00 Christian Mesh <notifications@github.com>:
