### ISSUE TITLE
Add support for Magneticraft iron pipes to fluid loader/unloader

### ISSUE THREAD

**Issue by WrongWeekend** [cam72cam/ImmersiveRailroading#282]
Currently Magneticraft's pipes do not work with the fluid loader/unloader in the same way IE's pipes do.

**Comment by cam72cam** [comment]
@WrongWeekend now that I have made some changes to the loader/unloader code could you verify that this is still an issue?

**Comment by WrongWeekend** [comment]
Seems to be working fine now. Thanks!
