### ISSUE TITLE
Allow boiler explosions without environmental damage

### ISSUE THREAD

**Issue by WrongWeekend** [cam72cam/ImmersiveRailroading#284]
Players should be able to run steam locomotives with the risk of boiler explosions, but without destroying blocks around them. The explosion should heavily injure and likely kill anyone nearby including those on board the locomotive, but not create an unrealistically huge crater in the ground.

**Comment by Milii20** [comment]
i highly suggest this too, but please, make it a config option, it will be a great idea for some packs, but some people would love to turn it off (like it happen with for example, channels from ae2, some people love it, some people hate it, the config option makes them all happy)

**Comment by EScapeTheShadows** [comment]
As a temporary fix till this is working, set domobgrief to false
