### ISSUE TITLE
shift right clicking with manual not working not sure what I am doing wrong

### ISSUE THREAD

**Issue by MacGabhann** [cam72cam/ImmersiveRailroading#285]
i have followed the wiki and even tried using crl and alt in place of shift just in case but can not get the manual to switch to the other ghost images also I am using the most up to date version of Immersive Railroading for minecraft 1.12.2

**Comment by cam72cam** [comment]
Try shift + clicking while looking in the air

**Comment by MacGabhann** [comment]
ah that did it thank you
