### ISSUE TITLE
Rendering Issue Causing Crashes with 1.0.0

### ISSUE THREAD

**Issue by qwryzu** [cam72cam/ImmersiveRailroading#286]
Since upgrading to 1.0 I've been getting random crashes and give me the same error: 

The game crashed whilst rendering entity in world
Error: java.util.ConcurrentModificationException

Sometimes the crashes happen every 2 minutes, sometimes I play for an hour without issue. It usually happens while loading chunks with trains in it.
Forge crash report is attached at the bottom. I did add a few new mods in the past few days but from what I understand in the crash report (very little), it's something with IR.

[crash-2018-04-03_12.46.24-client.txt](https://github.com/cam72cam/ImmersiveRailroading/files/1873113/crash-2018-04-03_12.46.24-client.txt)

**Comment by cam72cam** [comment]
Hmm, some other is changing the loaded entity list in the wrong thread I believe.  I think I can find a way around this.

**Comment by cam72cam** [comment]
Can you give http://174.138.127.16:8080/job/Immersive%20Railroading/164/artifact/build/libs/ImmersiveRailroading-1.0.0_1.12-164.jar a try?

It is the 1.0 release + a possible render fix

**Comment by Njet75** [comment]
Getting same crash.
Will test the new file and get back.
/Michael

**Comment by cam72cam** [comment]
@qwryzu I am marking this as closed, let me know if the issue persists
