### ISSUE TITLE
Cannot Feed Fluid Loader on Narrow Gauge Tracks

### ISSUE THREAD

**Issue by Rashaln** [cam72cam/ImmersiveRailroading#287]
You can't feed the fluid loader with narrow gauge tracks, as the track will break without a solid block under it, and it does not count pipes as solid blocks.

...Except when it does work. Spent 15 minutes trying anything I could think of to get it to work, no luck. Start writing this and then it works. Good, an intermittent issue. The best kind of issue. Seems like most of the time it doesn't work, though.
Version 1.0.0 for Minecraft 1.12.2, multiplayer.

**Comment by ahbit** [comment]
Latest version, works fine with stuff under the track.
You can remove blocks under the track, up to 10%.
I have this working in NG, with 1.12.2 and 1.0.0, and multi-player.

**Comment by cam72cam** [comment]
Try using a longer track.  The longer the track the more blocks under it you can break without hitting 10%.
Or update the config file

**Comment by Rashaln** [comment]
Whoops, sorry. Must have been a rounding error, I guess. I was using 10-block-long rail segments and removing one block.
