### ISSUE TITLE
Placing Track World Corruption

### ISSUE THREAD

**Issue by qwryzu** [cam72cam/ImmersiveRailroading#291]
I placed a piece of track down and then the track did the particle effect and made the sound that happens when you break a block. Then Minecraft promptly proceeded to crash. Now every time I load the world it works for about 10 seconds. The spot where I placed the track is empty, but it still does the particle effect and makes the sound. Then crashes. Crash report is attached at the bottom. If the world is salvageable somehow that would be great, I'm guessing I'll just have to uninstall IR and load the world and see if it still crashes.

[crash-2018-04-09_21.35.20-server.txt](https://github.com/cam72cam/ImmersiveRailroading/files/1892857/crash-2018-04-09_21.35.20-server.txt)

**Comment by Ommina** [comment]
Before removing IR and losing all your IR-related blocks, try setting forge's B:removeErroringTileEntities to true to see if you can get away with losing just the one TileEntity instead.

This doesn't speak to what is causing the underlying StackOverflow, but might get you going again without losing a mod's worth of progress.

**Comment by cam72cam** [comment]
Can you upload your world for me to test with?  It's an odd race condition that will be hard to debug without the erroring world.
