### ISSUE TITLE
[Suggestion] Increase Blueprint Blast-Resistance

### ISSUE THREAD

**Issue by hayesj1** [cam72cam/ImmersiveRailroading#294]
What's more annoying than a creeper blowing up your blueprinted track? A creeper blowing up a blueprinted segment whose position was meticulously tweaked. Vote yes on "Increase the blueprints' blast resistance"!

**Comment by redgoblin88** [comment]
because they are only a planned area, i think they shouldnt be able to be blown up at all however i bet the reason why they are "explodable" is because it is only rendering as semi-transparent and not as an actual sepperate track model/type compared to a properly placed fully formed rail.

**Comment by hayesj1** [comment]
I figured as such, but thought I should ask anyways.

**Comment by cam72cam** [comment]
Changing the blast resistance setting should be fairly easy
