### ISSUE TITLE
Can not use loaders/unloader augments with Minecraft scale trains

### ISSUE THREAD

**Issue by Astewen** [cam72cam/ImmersiveRailroading#297]
So far I'm really loving this mod! As both a train lover and a Minecraft lover I would like to help out (I do have 3D solids experience and program in Java professionally), but for now I'll play tester.

I like the Minecraft scale trains since I won't be riding them, but using them for automated transport. the problem is... you cannot place pipes under the loaders/unloaders at that scale. When you place the track, then place the loader/unloader augment all is well until you break the block under the augment to place the pipe - it destroys the track and augment (well, "un-places" them). How can I pipe items and fluids through the augments if I cannot place the pipe (or conduit or duct, or whatever) under the augment? I cannot pre-place the pipe either because then it won't let me place the track. Maybe a special case where breaking a block under an augment doesn't destroy the track? Suggestions?

**Comment by spacek531** [comment]
It is my understanding that pipes are not meant to go underneath the augment but beside them. Here is my setup:

![image](https://user-images.githubusercontent.com/3454156/38845448-4f931eae-41ac-11e8-9ca9-fee8d670e13d.png)

**Comment by Astewen** [comment]
Thanks spacek531, but it doesn't work when I try it. It looks like you have Narrow Gauge there? When I use Minecraft gauge (one block wide track) and place the pipe or hopper feeding the augment, the rolling stock or engine destroys them for being too close to the tracks. If I place them one block further from the track then it doesn't connect to the augment at all (well, there is one block of air between them). I can get it to work at larger gauges, just not the Minecraft gauge. In one of the spotlight videos he fed the augment from the underside with Standard Gauge, which works fine since you're only knocking out one of the 3 blocks wide below the track, but in MC Gauge there is only one block so I can understand why it happens, just not how to get around it and load/unload the trains.

**Comment by Astewen** [comment]
BTW, it works fine feeding from underneath with the Narrow Gauge.
![2018-04-16_23 05 52](https://user-images.githubusercontent.com/28109742/38846533-dbaf94a8-41ca-11e8-8305-6d2c80e3ad9d.png)

**Comment by Astewen** [comment]
I found a workaround. In the config file set `requireSolidBlocks=false` then in the game, dig the hole, place the conduit then place the track over it, finally place the augment between the conduit and the track. The conduit connects up to the augment and the track stays in place!

**Comment by spacek531** [comment]
I thought an angle might be an edge case, since the block wasn't broken with the broad gauge loco. 
![image](https://user-images.githubusercontent.com/3454156/38850408-24d4a358-41c6-11e8-8a9e-f1d87abb7727.png)

![image](https://user-images.githubusercontent.com/3454156/38850443-4a5d98c8-41c6-11e8-902e-d4eaa47ff754.png)

The block-breaking abilities of the rolling stock is most definitely determined by their hitboxes.

What these hitboxes are, I don't know, as parts of the Rogers tender definitely interfere with trackside blocks in standard gauge.
![image](https://user-images.githubusercontent.com/3454156/38850484-7cd4e130-41c6-11e8-8692-d8917f43e594.png)
