### ISSUE TITLE
22.5 to 45 diagonal transition

### ISSUE THREAD

**Issue by qwryzu** [cam72cam/ImmersiveRailroading#303]
When you have diagonal track at a 22.5 degree angle with a 22.5 turn at the end which leads into a track at 45 degrees, trains don't follow the curve well. Picture attached below. Orange wool is to show which way straight track with no angle is. You can see that the trains don't quite follow the curve, they only line up with the track again when they get back onto straight track. If this explanation and picture doesn't quite communicate the issue, I can film a video too.

![2018-04-26_20 49 55](https://user-images.githubusercontent.com/27305244/39343757-71fb2876-4993-11e8-96cd-754cb05a4051.png)

**Comment by cam72cam** [comment]
Yeah, this is a known issue.  I have been having a hard time figuring out where in the math this happens

**Comment by qwryzu** [comment]
Fixed in experimental build B
