### ISSUE TITLE
Possible Conflict with runtime environment 

### ISSUE THREAD

**Issue by Spr18JSyiFMR** [cam72cam/ImmersiveRailroading#304]
I'm not sure what's causing it but when I updated the Java RE to the 1.8.0 171 patch, the game would load the main menu but fail to load the world dumping this file into my minecraft folder: 

[hs_err_pid15260.log](https://github.com/cam72cam/ImmersiveRailroading/files/1957344/hs_err_pid15260.log)

Removing ImR does fix the issue. I've Tried rolling back the RE to 1.8.0 161 but I've had no success in getting it to work.

Forge Mod Loader version 14.23.3.2675 for Minecraft 1.12.2
Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_171

ImmersiveRailroading-1.0.1_1.12
ImmersiveEngineering-0.12-81
TrackAPI-1.1_1.12

**Comment by cam72cam** [comment]
It looks like you have an intel GPU and recently updated your graphics driver. Try rolling that back

**Comment by Spr18JSyiFMR** [comment]
I just looked the Device manager and found that i have 2 display adapters. The intel and a Nvidia. I then remembered that I forced the game to use the nvidia in the past to boost the FPS. When I updated Java it might have undid the settings I had applied to the RE. So I'm going to see if setting the RE to use the NVIDIA that fixes the issue before I roll back anything.

**Comment by Spr18JSyiFMR** [comment]
Okay I just switch which GPU is use for the RE and it works now! I'm going to make a note about this in my troubleshooting folder.
Thank you for your help!
