### ISSUE TITLE
No machinery

### ISSUE THREAD

**Issue by GummYstuff** [cam72cam/ImmersiveRailroading#305]
I downloaded the mod, and started wondering why i couldnt find the steam hammer/plate roller/boiler roller etc as well as the ethanol bucket (found out ethanol bucket was part of immersive engineering). I still cant find the steam hammer and other machines in my game? how do i get them?

**Comment by Larky2k** [comment]
there multiblock structures, make the IR book and also watch cams YT vids

**Comment by GummYstuff** [comment]
thanks

**Comment by cam72cam** [comment]
https://youtu.be/JlqJf7x04Ys?t=550
