### ISSUE TITLE
Looping and Quilling whistle/horn support

### ISSUE THREAD

**Issue by CalocoDoesGit** [cam72cam/ImmersiveRailroading#315]
Currently whistles and horns are a set lenght.
It would be nice if we would be able to hold the horn button down for continues activation along with holding a secondary button for a quill.

This way users have more controll over there whistle/horn patterns.

**Comment by Thomas4peyton** [comment]
quilling will most likely be supported, because every whistle has diff levels of quilling.  Two and Three part horns are planned for 2.0 so I will move this request there.
