### ISSUE TITLE
Ability to Mute Locomotive Horns

### ISSUE THREAD

**Issue by qwryzu** [cam72cam/ImmersiveRailroading#316]
When trains with multiple locomotives go over a horn augment, it's really annoying how they all play the sound. It would be cool to be able to turn off horns on individual locos so you only have to hear the horn play once. I'm no coder, but it seems to me that adding a mute key would be easier than making it automatically detect coupled locomotives and only play one horn. Plus it would be much more versatile, so you can pick and choose which specific locomotives you want to play the sound (powerful locomotive with ugly sounding horn coupled to weak locomotive with good sounding horn = powerful and pretty sounding)

**Comment by cam72cam** [comment]
This can be done by clicking on the augment with the locomotive type you want to whistle

**Comment by CalocoDoesGit** [comment]
Wouldn't that still be an issue with 2 of the same locomotives in the consist?

**Comment by cam72cam** [comment]
At that point you should be using OC and tags
