### ISSUE TITLE
Vivecraft exposed rendering glitch

### ISSUE THREAD

**Issue by shadowbolt79** [cam72cam/ImmersiveRailroading#321]
Tracks and items models all render fine while using IR with Vivecraft:

https://cdn.discordapp.com/attachments/195502278508150784/450823791619080192/unknown.png

But the moment I place a train on the tracks everything begins to smear, and the pause menu double renders:

https://cdn.discordapp.com/attachments/195502278508150784/450823847734673409/unknown.png

Issue persists even to the main menu screen, requiring a restart in order to fix:

https://cdn.discordapp.com/attachments/195502278508150784/450824388992958464/unknown.png

This suggests there is an opengl state being changed in the entity renderer that is not being reverted to previous value, possibly dealing with depth.

If you want to attempt to tackle this issue, I will be available to test.

**Comment by cam72cam** [comment]
Does it happen with just steam locomotives or does it happen with the simpler models as well?

**Comment by cam72cam** [comment]
Looking through my code again, the only weird thing I do is render an entity when already inside a render entity.  Can you try setting B:useShaderFriendlyRender=false?

**Comment by shadowbolt79** [comment]
Set down the pepper's hopper car and it did the same thing with 'B:useShaderFriendlyRender=false'

https://cdn.discordapp.com/attachments/437274968380932098/452654210169962508/unknown.png

**Comment by cam72cam** [comment]
Closing as won't fix
