### ISSUE TITLE
track segment's borders attached to the blocks

### ISSUE THREAD

**Issue by DerHurenSohn** [cam72cam/ImmersiveRailroading#325]
Hello guys. I wanted to ask you make track segments more fit to minecraft blocks so that the both endings of each segment were exsactly in the middle of the block and every next part of the track would smoothly connected to the previous one. This could be useful e.g. for subway building where tunnel's are made of minecraft blocks and tracks need to lay strictly in between the walls so that trains won't hit it. Is this even possible to implement, or at least make it possible to choose this kind of track laying in config/blueprint menu?

**Comment by cam72cam** [comment]
Sorry, this is not possible
