### ISSUE TITLE
Turn Track placement bug: directional differences

### ISSUE THREAD

**Issue by Lightwave413** [cam72cam/ImmersiveRailroading#329]
https://i.imgur.com/TQhIHRC.png

Both sides were placed with the same track blueprint with the same settings, the left half was placed leftways (counterclockwise) and the right half was placed rightways (clockwise).

Tested on 1.2.0

**Comment by DerHurenSohn** [comment]
+1
See how different seems 30m 22.5 deg. turn depending on its direction.
![screenshot 618](https://user-images.githubusercontent.com/34898566/41189418-449544e2-6bd6-11e8-8eef-5621ff703a1a.png)
Also left oriented turn is thinner than right turn.
Rail blocks on the left turn:
![screenshot 619](https://user-images.githubusercontent.com/34898566/41189435-94a74b7e-6bd6-11e8-8fab-f2ff64ac9a4c.png)
![screenshot 621](https://user-images.githubusercontent.com/34898566/41189437-9a4167e0-6bd6-11e8-87aa-4c158908ca12.png)
![screenshot 622](https://user-images.githubusercontent.com/34898566/41189439-9d2f7a46-6bd6-11e8-8168-40d42553345a.png)
Similar position on the right turn:
![screenshot 623](https://user-images.githubusercontent.com/34898566/41189449-d4aa9b90-6bd6-11e8-9815-b5cfac51bf4d.png)
![screenshot 624](https://user-images.githubusercontent.com/34898566/41189450-d7679cd4-6bd6-11e8-8ae0-d7f5cb010aef.png)
![screenshot 625](https://user-images.githubusercontent.com/34898566/41189451-d9e88536-6bd6-11e8-9c72-5e7663d641ca.png)
Can it be any radius bug which counts different radius for each direction?

**Comment by cam72cam** [comment]
Thanks for the detailed report.  Some other users complained about this and I found a solution a day or so ago.  I'll be doing a release in the next few hours to address this.

In the mean time you can try the latest dev build which should fix it: http://174.138.127.16/job/Immersive%20Railroading/202/artifact/build/libs/ImmersiveRailroading-1.2.0_1.12-202.jar
