### ISSUE TITLE
Requesting Track overhaul to use both standard placing and markers for other users.

### ISSUE THREAD

**Issue by trainman264** [cam72cam/ImmersiveRailroading#34]
Basically, me and trainzfans and some others in the train group that It would be a good Idea to have it set to where you could use the tracks manually if you wanted and for others, use track markers.

**Comment by trainman264** [comment]
![image](https://user-images.githubusercontent.com/31801827/30245081-c2be30d8-9583-11e7-8816-a7058c2887ee.png)

**Comment by trainman264** [comment]
![image](https://user-images.githubusercontent.com/31801827/30245091-f6e00468-9583-11e7-9761-df876c642463.png)
![image](https://user-images.githubusercontent.com/31801827/30245095-0f5a011a-9584-11e7-98f0-fd488b0ce1ba.png)
![image](https://user-images.githubusercontent.com/31801827/30245098-2117a948-9584-11e7-8231-eab387c7a752.png)
Many of us where thinking that doing an marker system and keep the current system would be really nice. its almost like having Flex track as well as regular standard track to place

**Comment by DonBruce64** [comment]
Will see about fixing my system and making it a stand-alone lib.  I don't want to make MTS a dep for flex track.  Deps for features are hazardous to update schedules.  Especially with MTS's current timetable.

**Comment by cam72cam** [comment]
We now have support for the TrackAPI in IR.  Don has pushed his code to https://github.com/DonBruce64/OpenFlexiTrack/.  Once his track supports the TrackAPI for movement this will be possible.  Either he or I will work on that at some point.
