### ISSUE TITLE
Suggestion: Changing Redstone Control of Loco Control parts

### ISSUE THREAD

**Issue by DorniNerd** [cam72cam/ImmersiveRailroading#343]
Possible to change it so redstone signal 1-14 is 0-100% on whatever the control is set to change... But at level 15 redstone strength, the control part is disabled. This would allow an automatic train system to operate as well as allow player controlled trains to run over the control unit without affecting the player set throttle or brake settings.

**Comment by cam72cam** [comment]
If you need that level of control, use open computers

**Comment by DorniNerd** [comment]
For the less LUA (or coding) savy individuals, and much stronger Redstone oriented members, was the only reason I asked. But appreciate it regardless.
