### ISSUE TITLE
Fix trains disappearing when looking off of it slowly

### ISSUE THREAD

**Issue by trainman264** [cam72cam/ImmersiveRailroading#35]

**Comment by cam72cam** [comment]
Found the bug.  World.MAX_ENTITY_RADIUS = 32 fixes it!

**Comment by cam72cam** [comment]
Nope, still an issue in a few edge cases. drat

**Comment by trainman264** [comment]
Damn

**Comment by cam72cam** [comment]
I think I found the issue now.  If a chunk is outside of your viewbox, minecraft does not iterate through the entities to render.  I am not sure how to fix that

**Comment by cam72cam** [comment]
I fixed it for the case that matters, when you are riding the entity.  Still kinda buggy when looking around when not riding, but it is close enough for now

**Comment by trainman264** [comment]
Hi,

I've just signed the following petition "Adam Danser: Students wearing
black pants" and wanted to see if you could help by adding your name.

Our goal is to reach 500 signatures and we need more support. You can
read more and sign the petition here:

https://chn.ge/2BSzWmx

Thanks!
elijah

**Comment by trainman264** [comment]
Hi,

I've just signed the following petition "Adam Danser: Students wearing
black pants" and wanted to see if you could help by adding your name.

Our goal is to reach 500 signatures and we need more support. You can
read more and sign the petition here:

https://chn.ge/2MQZBR7

Thanks!
elijah

**Comment by km00700** [comment]
That's... kind of arbitrary...
