### ISSUE TITLE
Changing Cargo Loads with Inventory Capacity

### ISSUE THREAD

**Issue by km00700** [cam72cam/ImmersiveRailroading#351]
Using the quantity of items in the inventory of a cargo car, have the option for cullable cargo objects named: CARGO_FILLED_0, CARGO_FILLED_25, CARGO_FILLED_50, CARGO_FILLED_75, CARGO_FILLED_100. Each would become visible as the inventory reaches or goes above the stated percentage of capacity. This would allow modelers to make loads that appear to increase as the car fills up.

**Comment by Larky2k** [comment]
can be easily done using one object called LOAD

**Comment by km00700** [comment]
With multiple objects, there is the ability for multiple capacity levels

**Comment by Larky2k** [comment]
you can do it with 1 object and have it moulded to the space it will occupy you can have it define as 100% and have the renderer move the texture up or down to indicate how much is in there and would show the space filling up. FriedrichLP Eternal doing as similar system for TC you can ask him for pointers on how to do it
