### ISSUE TITLE
Levers won't work with angled switches

### ISSUE THREAD

**Issue by Railroadactive** [cam72cam/ImmersiveRailroading#355]
I placed down a switch on a 45 degree angle, but when I tried to place a lever to flip the switch, nothing worked, I tried every block close to the switch rod by the points but I couldn't seen to get it to work.

**Comment by Railroadactive** [comment]
It turns out I was not trying hard enough, I laid down two angled switches in creative and both of them worked, then I went back to my survival world tried again and it still didn't work, I relaid the switch to no luck but then I dug under the track beneath the rod and placed it there and then it worked.

**Comment by cam72cam** [comment]
yeah, I still need to expand the detection for angled switches
