### ISSUE TITLE
Laying standard rails

### ISSUE THREAD

**Issue by steveknorris** [cam72cam/ImmersiveRailroading#361]
could you please tell me how do I get the rail to slope down. I have waited for a top class rail system to come out in Minecraft for 10 years now, thank you I have tried each one as it came out and then dumped it after a few weeks but yours I can now do the system I have dreamed of again thank you,
steve

**Comment by FriedrichLP** [comment]
You can’t place a slope downwards. Instead you just place a lope upwards and go on the lower position where the down slope would end. Just ask in our discord when you need more help.

**Comment by steveknorris** [comment]
Thank you

**Comment by LeahPike** [comment]
Would be great if you could use crouch when placing a slope to make it go down instead of up, I find making downwards slopes hard work.
