### ISSUE TITLE
controls will notwork

### ISSUE THREAD

**Issue by Tangoandcash1** [cam72cam/ImmersiveRailroading#362]
hi
I have got 2 locos when I place them on the track on 2 occasions the control panel works but most of the time it will not work I press the dead man off no text show I press the brake the GUI shows no movement I press the throttle no movement the game crashes. the next time it could work ok, or do the same, any help please, sorry for the inconvenience and thank you for your help
Steve Norris

**Comment by FriedrichLP** [comment]
I cant do much with this information. Can you send me the crash report? Then I can take a look at it.

**Comment by Tangoandcash1** [comment]
the crash report is showing a java error (PMDescription: Unexpected error java.lang.NullPointerException: Unexpected error) I am using java 1.8.0.171
many thanks
Steve Norris

**Comment by Tangoandcash1** [comment]
[crash-2018-07-14_13.11.45-client.txt](https://github.com/cam72cam/ImmersiveRailroading/files/2194926/crash-2018-07-14_13.11.45-client.txt)

**Comment by Tangoandcash1** [comment]
hi I think I have solved the throttle problem the zero throttle control has been set to the (num lock key) and with the key having 2 states of keystroke it is locking out the loco control panel.
thank you
Steve Norris

**Comment by cam72cam** [comment]
That crash was from "mcjty.immcraft.network.PacketPlaceItem"
one of McJty's mods
