### ISSUE TITLE
TrackAPI Missing

### ISSUE THREAD

**Issue by bverailer** [cam72cam/ImmersiveRailroading#369]
I went to run the mod on 1.12 and I got an error message saying; "Immersive Railroading is missing mods it depends on. Include the following mods or remove Immersive Railroading : trackapi 1.1 or above". But no download link was included for trackapi

**Comment by WrongWeekend** [comment]
Track API is on Curseforge, same as IR.

https://minecraft.curseforge.com/projects/track-api

**Comment by bverailer** [comment]
Thank you!
