### ISSUE TITLE
Let the end user decide what kind of resource packs they what to use

### ISSUE THREAD

**Issue by stlsf4003** [cam72cam/ImmersiveRailroading#382]
Basically have it set up so that the mod only comes with the track and crafting equipment. 

That way the end user is free to pick and choose from whatever resource pack the please. It would also help make to mode a bit easier to load up if it just came with the basic tools to get you going.

And for those how don't want unused locomotives and cars taking up space in the game, just set up a config feature that lets the user disable any piece of rolling stock that don't plan on using.

**Comment by km00700** [comment]
Note: Perhaps keep the handcar and/or small mining loco as a starter.

**Comment by cam72cam** [comment]
I will always be shipping IR with the current base set of locos, don't plan on reducing it.  You can setup a resource pack with a black list to remove stock if you want.

See the LowResourcePack for an example: https://github.com/cam72cam/ImmersiveRailroading/tree/master/resourcepacks
