### ISSUE TITLE
[1.3.1_1.12] IR overrides OC beep sound

### ISSUE THREAD

**Issue by LiEyWe** [cam72cam/ImmersiveRailroading#385]
As the title says, Immersive Railroading overrides the OpenComputers beep sound.
Instead, the noteblock sound plays.

**Comment by LiEyWe** [comment]
Installing a sound overwriting mod like DynamicSurroundings removes this problem.
I tested IR's sounds with the hi-rail truck from the super liners pack at max speed and everything seems normal.

**Comment by cam72cam** [comment]
Try setting B:overrideSoundChannels=false

I think I set the default wayy to high
