### ISSUE TITLE
New Japanese Translation

### ISSUE THREAD

**Issue by gaojie429** [cam72cam/ImmersiveRailroading#388]
Hi, I found some items in ver1.3.2 isn't translated into Japanese.
So I made a new Japanese translation file for 1.3.2. Could you add this file to your next version?

[ja_JP.lang.zip](https://github.com/cam72cam/ImmersiveRailroading/files/2259631/ja_JP.lang.zip)

**Comment by cam72cam** [comment]
Definitely, thanks for the contribution!
