### ISSUE TITLE
Rolling stock does not exist on server.

### ISSUE THREAD

**Issue by MarkL4YG** [cam72cam/ImmersiveRailroading#401]
Hello there,

we've created a modpack which includes IR but we're facing issues with ``Rolling stock does not exist on the server. Can not place``.  
As far as I've seen from the source code that would mean the train definition is missing on the server.  
What I don't get is how this can be the case when we're using Solder and load the exact same modpack and mod versions on both client and server and how even the default trains could be missing.  

I have copied the debug server logs into [a gist](https://gist.github.com/MarkL4YG/335455b47880ba2809236163ccb70d73) in case they could be useful to you and below is some general information about our setup.

I've noticed the following warning right at the end of the definition loading.
``[21:58:59] [Server thread/WARN] [immersiverailroading]: -51131120 7492283784``.  
This however, is not very meaningful to me.

We have also added [this pack](https://minecraft.curseforge.com/projects/d-rgw-narrow-gauge-pack-ir) to the modpack although I'm not quiet sure how to load resource packs on servers 🤔 

If you don't have an exact idea on what is going wrong I would welcome advise on further debugging options to trace this.  
And of course I'm willing to provide any information of relevance I may have missed.

Best regards

## General Info
Forge Version: forge-1.12.2-14.23.4.2739
SpongeForge Version: spongeforge-1.12.2-2705-7.1.0-BETA-3361
IE version: 0.12.84
IR version: 1.3.2

**Comment by EScapeTheShadows** [comment]
unless i am misunderstanding how you did this, you have the resource packs under the resource packs folder on the server, correct? if so, that is your problem, as they go under a difference folder. i believe the file path is immersive railroading-resource packs, but i may be wrong about this, so you may want to double check the correct file path up online.

**Comment by km00700** [comment]
Server resource packs go in config/immersiverailroading.

**Comment by EScapeTheShadows** [comment]
Figured i had the path wrong, thanks for correcting KM

**Comment by km00700** [comment]
It's not the most intuitive place for many users, but it's what works on servers. (The default call to load packs is not called serverside)

**Comment by MarkL4YG** [comment]
Well, that explains a lot.  
Thank you very much for your response.
Will test out tomorrow :)

**Comment by MarkL4YG** [comment]
After moving the two packs and the IR jar into ``config/immersiverailroading`` it now seems to work as expected.  
Again thank you for your help. 👍

**Comment by Cidatis** [comment]
I having the same problem when I try to place trains (tracks work). it says in chat "Rolling stock does not exist on server. Can not place Ensure you have installed the recourse pack in the server's config/immersiverailroading folder." Please help me with this issue. I don't what recourse pack I need to put in my server config. Also my server runs of my pc not aternos.

Info
Client Forge version: 1.12.2 - 14.23.5.2855
Server software: Magma v761933c-CUSTOM
IR Version: 1.9.1

**Comment by Larky2k** [comment]
Then your out of luck as RP must got on the IR config folder to work on server

**Comment by Cidatis** [comment]
> Then your out of luck as RP must got on the IR config folder to work on server

Sorry, I don't get you. I am just asking what needs to be place in the config/immersiverailroading folder, I am new to modding servers so I don't know what you are talking about.

**Comment by km00700** [comment]
IDK what larky's talking about. You need to place the resource pack zip files for any IR addon packs that you're using on your clientside into the config/immersiverailroading folder of your server.

**Comment by Cidatis** [comment]
I don't have any addon packs.

**Comment by km00700** [comment]
what are you trying to place?

**Comment by Cidatis** [comment]
the default trains.

**Comment by km00700** [comment]
Have you tried with a freshly downloaded copy of the IR jar on the server?

**Comment by Cidatis** [comment]
you mean from curse?

**Comment by Cidatis** [comment]
Sorry if I didn't get you.

**Comment by km00700** [comment]
yes.

**Comment by Cidatis** [comment]
Yeah I have a fresh copy from curse on the server and on my client.

**Comment by km00700** [comment]
And does it work on a non-magma server setup? Magma has been known to cause all kinds of incompatibility issues with IR.

**Comment by Cidatis** [comment]
well let me explain why I use magma instead of forge. So basically I open the forge jar file. Set the path for the server files I run the server.jar. do the other things needed, and there is no mods file, so I create a new one and don't think much of it and put the mods in, but when I start the server and join it. I can't place any modded blocks.

**Comment by Cidatis** [comment]
and so you don't need to tell me, I do have java 8

**Comment by km00700** [comment]
that means you haven't been running the forge server jar

**Comment by Cidatis** [comment]
I did run the forge server jar before, but nothing pops up.

**Comment by km00700** [comment]
ok, but Magma might be causing your issue. I'd attempt to get forge server jar to work before relying on Magma.

**Comment by Cidatis** [comment]
Ok.

**Comment by Larky2k** [comment]
read the last line your wrote on first post, you have worded it wrong. that's why what iv said

**Comment by Cidatis** [comment]
wait, I can't open the forge.jar thing.

**Comment by km00700** [comment]
what's the filename?

**Comment by Cidatis** [comment]
forge-1.12.2-14.23.5.2831-installer.jar

**Comment by km00700** [comment]
that's not the server. That's the installer. Shouldn't be inside your server directory.

**Comment by Cidatis** [comment]
no, what I mean is I can't open the installer to get the server files.

**Comment by km00700** [comment]
does it just not open? or does it crash?

**Comment by Cidatis** [comment]
It does not open, all that happened was it did the loading circle think for the windows 10 cursor when you open a application.
