### ISSUE TITLE
immersiverailroading.render.entity.MagicEntity causing frame lag?

### ISSUE THREAD

**Issue by galaxy119** [cam72cam/ImmersiveRailroading#406]
![image](https://user-images.githubusercontent.com/10914157/44008166-121df480-9e55-11e8-984c-4cab4a795d6a.png)
What is "render.entity.MagicEntity", what does it do, and why does it require so much frame draw time?

**Comment by km00700** [comment]
The MagicEntity is an entity rendered by ImmersiveRailroading located on the player. It keep the tracks and locomotives rendered across chunk borders. You may have seen other mod's large entities disappearing if the center is off your screen. The MagicEntity tricks the client into rendering everything.

**Comment by galaxy119** [comment]
The odd thing is, it seems to only be a problem when I'm in my base. When out in the wild, I'm at 130+ fps and the magic entity is only at 20-25k ns/Frame, but in my base it jumps up to close to 1 sec/frame (usually 590-920k ns/frame)

Is this simply because my base has more stuff than the wilderness? Is there any way I can solve this? I personally don't even use the mod, but it's part of the server because one of the Moderators is dedicated to everything Immersive related, but it's causing me (and the other person living in my base) big issues for seemingly no reason.

**Comment by km00700** [comment]
how much RAM have you allocated, and what are your system specs?

**Comment by galaxy119** [comment]
I don't know if that low of an amount of RAM will even be runnable, the modpack we are running is *very* large. But I'll try lowering the ram amount and see where that gets me, though I'm not very sure lowering it to below what it normally sits at will be helpful at all.

**Comment by km00700** [comment]
Lower it until you regularly use about 70-80% of the allocated RAM.

**Comment by galaxy119** [comment]
Well, at 12gb allocated, avging 9gb used, that's 75% usage.  But I'll lower it a tad and see how it goes. 

But the issue seems to stem from the fact that immersive railroad's magic entity jumps from 20-30k ns/frame to 500k+ ns/frame when in the base. I would *assume* since I have no immersive anything in my base, this would be a bug on the mods end, as the FPS drop affects anyone on the server who comes into the base, though removing Immersive Railroading completely is a big leap,  may give t a go on a backup world in SP and see what happens after I test running with less RAM.

**Comment by km00700** [comment]
which version of IR are you using?

**Comment by galaxy119** [comment]
1.3.2.

As suspected, reducing the allocated ram by any amount less than it's normal consumption just tanked my game performance, increasing it back up so about 75% of it's allocation is used brought it back up to how it was, going to try removing IR on a backup of the server world and see how it does

**Comment by km00700** [comment]
IR should be able to render a few hundred pieces of stock without any drops in performance.

**Comment by PyroskE1987** [comment]
Are you running any shaders or texture packs?

**Comment by km00700** [comment]
those wouldn't add much specifically, although I haven't heard of the MagicEntity itself slowing.

**Comment by galaxy119** [comment]
Texture pack Chroma Hills and KUDA shaders, the problem is persistent with and without them both on. 

Testing in the backup world VIA Single-Player went as follows. 

With IR installed: 2mins after loadup: Looking out front door of base, 28FPS. Turn around to face center of main room: 13FPS.

Without IR Installed, same world: 2mins after Loadup: Looking out front door of base, 48FPS. Turn around to face center of main room: 35FPS.

Using LagGoggles shows me that IR's MagicEntity was using 512k ns/frame at the first FPS point and 1.4s/frame at the second.

LagGoggles shows that in both tests, the other frame render entities took approxamately the same amount of overall time to render during both tests (each was +/- 5% in ns/frame but overall excluding MagicEntity it was actually about 300ns/frame faster during the first test at both FPS points.

**Comment by galaxy119** [comment]
The lag spike seems to emanate from X 1413, Y 78 Z -509 (That is, standing with my head in that block looking in any direction results in 30+ FPS, but looking directly at said block results in 15-25FPS  Which is part of my Draconic Evolution Battery multiblock, but neither deactivating the multiblock nor removing all of the draconic materials used for it, or replacing that block seem to fix anything.    The lag spike is still somewhat noticeable looking at the block without IR installed, but *much* less drastic. from a 20-30FPS loss down to a 5-10fps loss.

**Comment by km00700** [comment]
then are you sure the issue is _caused_ by IR. There is a config setting that causes the client to do additional calculations if there is lag on the server/ Since you still have some fps drop without IR, that looks probable.

**Comment by galaxy119** [comment]
I'm unsure if the root cause of the lag is IR, all I know is IR was making the lag spike render the area nearly unplayable, so this is where I came as it's the only specific mod that I could tell was causing any issue at all.
Where's this setting so I can mess around with it?

**Comment by km00700** [comment]
in the config

**Comment by galaxy119** [comment]
I'll try disabling it and going back to my server client and let you know how it behaves.

**Comment by galaxy119** [comment]
Disabled the setting both client and server side, restarted both after the change.  Still this
![image](https://user-images.githubusercontent.com/10914157/44010993-ae012cf4-9e6a-11e8-9683-6c75bf411a1d.png)
![image](https://user-images.githubusercontent.com/10914157/44011007-c5f8ba2a-9e6a-11e8-818d-e317aa8023c1.png)
![image](https://user-images.githubusercontent.com/10914157/44011017-d4a5734c-9e6a-11e8-8566-09e6777fee06.png)

**Comment by km00700** [comment]
and any screenshots with the debug screen?

**Comment by galaxy119** [comment]
![image](https://user-images.githubusercontent.com/10914157/44011221-2c661446-9e6c-11e8-8fc3-6d17b03e195e.png)
![image](https://user-images.githubusercontent.com/10914157/44011237-48caef8a-9e6c-11e8-8fa7-d9a242c5e82a.png)

**Comment by km00700** [comment]
something inside is causing 25 chunk updates/second

**Comment by cam72cam** [comment]
Looking at the lag goggles report, the problem is not IR.  1% of frame time is negligible.

Some other mod is causing that issue and it is not showing up in lag-goggles.
