### ISSUE TITLE
Union Link doesn't Work anymore fellas, what happen there?

### ISSUE THREAD

**Issue by trainman264** [cam72cam/ImmersiveRailroading#424]
![f6e7918a86d8ed1489063b9181d74105](https://user-images.githubusercontent.com/31801827/45060829-bb989e80-b06f-11e8-85ec-97b55b7a0bd2.png)

**Comment by cam72cam** [comment]
Have not touched that code in a long time.  Have you checked your other locomotives?

**Comment by trainman264** [comment]
Yeah, there defiantly an issue of some sort

**Comment by trainman264** [comment]
Did the Union link ever move?

**Comment by cam72cam** [comment]
I don't think I supported that yet TBH
