### ISSUE TITLE
Some switches destroyed after update

### ISSUE THREAD

**Issue by Railroadactive** [cam72cam/ImmersiveRailroading#427]
I just updated the mod to 1.3.0 but when I logged on to my world, some of the switches were destroyed, leaving the rails and ties on the ground, and I can't seem to get things to fit the way they were.

**Comment by km00700** [comment]
Which version did you have before? There was one version in which we update how trackage works

**Comment by Railroadactive** [comment]
I updated front he 1.2.0 version and already had relaid some track and switches but I did not see the warning for updating up to the 1.3.2.

**Comment by cam72cam** [comment]
Did you make any changes to the configs?  Sometimes the configs get reset on version updates

**Comment by Railroadactive** [comment]
I changed the configs to allow deep snow and so model trains don't require fuel. Other than that I don't remember fiddling with them but I also did try fiddling around to make the manual use of the horns work.

**Comment by cam72cam** [comment]
hmm, odd.  sorry about that
