### ISSUE TITLE
1.12.2 supported?

### ISSUE THREAD

**Issue by StarSmasher44** [cam72cam/ImmersiveRailroading#428]
Wrong place to ask, I know, but it was the easiest and quickest for me so I have to ask;

Does this mod work on 1.12.2, and if not, when will it? I'd LOVE to throw this into my pack.

**Comment by EweLoHD** [comment]
![image](https://user-images.githubusercontent.com/22636066/45264208-434c2780-b439-11e8-8a37-dcfbb1c23604.png)
 And yeah this is really the wrong place to ask this.

**Comment by StarSmasher44** [comment]
Sorry, was going off of the curseforge which has 1.12, file name 1.12 and no mention of 1.12.2, my bad!
