### ISSUE TITLE
Cant find how to toggle switches

### ISSUE THREAD

**Issue by KronkIV** [cam72cam/ImmersiveRailroading#429]
I have searched all over and have not been able to find anything that says what is used or how to toggle a switch track. This is a very cool mod, but is often not intuitive.

**Comment by KronkIV** [comment]
Thank you, and thank you for the quick reply.
I have a 5-year old that is big into minecraft and trains and I am trying to set him up. Is there a way to make it so while in creative mode, the trains dont require fuel and water?

**Comment by km00700** [comment]
In the immersiverailroading config, there's an option called allGaugesRequireFuel.

**Comment by KronkIV** [comment]
thank you so much
