### ISSUE TITLE
List of Tools To Make

### ISSUE THREAD

**Issue by trainman264** [cam72cam/ImmersiveRailroading#43]
- [x] Steam Hammer
![hammer](http://www.blackiron.us/graphics/steam-hammer-fig3.gif)
- [x] Casting Machine
  - https://prrt1steamlocomotivetrust.org/videos/PRR%20T1%205550%204%20Wheel%20Cast.mp4
- [x] Boiler section rolling machine
  - https://youtu.be/UfS9O68lJHI?t=235
- [x] Track Rolling Machine
- [ ] Lathe
![lathe](https://upload.wikimedia.org/wikipedia/commons/thumb/e/e7/Ahrons_%281921%29_Steam_Locomotive_Construction_and_Maintenance_Fig30.jpg/450px-Ahrons_%281921%29_Steam_Locomotive_Construction_and_Maintenance_Fig30.jpg)
https://www.youtube.com/watch?time_continue=332&v=_kRQ3VhmApM
- [ ] Large Hydraulic Press ![Hydraulic](http://www.midcontinent.org/wp-content/uploads/1385_2014_07_06_d.jpg)

**Comment by cam72cam** [comment]
A primitive version of the steam hammer is in game

**Comment by cam72cam** [comment]
https://youtu.be/HvtOT-ea270?t=156
