### ISSUE TITLE
Items not showing up in car inventory after using item loader

### ISSUE THREAD

**Issue by Railroadactive** [cam72cam/ImmersiveRailroading#437]
I'm trying to load seeds and potatoes into the SLSF 70 ton hopper using an item loader. I've set the loader to only load the covered hoppers but the hopper loading the augment is empty but there is nothing showing up in the car inventory. I also have a conveyor loading the hopper that is linked to the item loader so items are entering the hopper but dissappear after that.

**Comment by cam72cam** [comment]
This was a bug in a prior version.  Make sure you have updated to 1.3.3

**Comment by Railroadactive** [comment]
I have yet to do that so thanks! :)
