### ISSUE TITLE
J1A Texas Class Not working

### ISSUE THREAD

**Issue by Gustav121** [cam72cam/ImmersiveRailroading#438]
When I place the J1a Texas and start the engine it haets up until 21,5 °C, then the game crashes and I can't join the world anymore

**Comment by FriedrichLP** [comment]
I guess your missing some sounds. Check again if the sounds are in the resource pack.

**Comment by FriedrichLP** [comment]
then remove the sounds from the locomotive json in rolling_stock/locomotives/texas. You can open the file with any text editing program (Notepad++ or the default notepad)
