### ISSUE TITLE
[1.12.2] Crash with "invalid item stack"

### ISSUE THREAD

**Issue by TheSnowyChickens** [cam72cam/ImmersiveRailroading#442]
Hello,

today I scrolled in the Better Questing menu for the Icon selection and I got a crash.
-> https://paste.dimdev.org/emolulovoh.mccrash

I ask under a BQ crash, if this is similar to the crash in the topic, but no.
The BQ Dev. "Funwayguy" can't rly do something to resolve this crash and so he told me, that I should report this crash to you. :=)
He also said, if he can help somehow, you/we can tag him.

Funwayguy last comment in case of my crash question:
"Considering I can't do a lot from my side (besides outright ignoring invalid items which would likely crash something else eventually anyway) it would probably be a better idea to send this to Immersive Railroading's GitHub tracker. If necessary you can tag me in it so I can add additional information if needed."

MC 1.12.2
Forge 2765
IE 85
IR 1.3.3
Track API 1.1

**Comment by km00700** [comment]
Yeah that seems to be another problem with item deserialization. Basically, all IR rolling stock pieces are the same item, so when the Minecraft ItemStack methods strip the NBT data, they all become the same thing and that causes all sorts of issues.

**Comment by Funwayguy** [comment]
It's not a de-serialisation issue. IR is forcing the stack size to zero when BQ is mid way through searching its name and tooltips.

Relevant line:
https://github.com/cam72cam/ImmersiveRailroading/blob/master/src/main/java/cam72cam/immersiverailroading/items/nbt/ItemDefinition.java#L20

**Comment by Funwayguy** [comment]
Same way the creative search tab obtains item stacks, or if the item is hidden from that tab, asking the item itself for its default instance.

Search Tab:
https://github.com/Funwayguy/BetterQuesting/blob/1.12/src/main/java/betterquesting/api2/client/gui/panels/lists/CanvasItemDatabase.java#L98

Default Stack:
https://github.com/Funwayguy/BetterQuesting/blob/1.12/src/main/java/betterquesting/api2/client/gui/panels/lists/CanvasItemDatabase.java#L113

Regardless of whether an item is missing data, forcing it to zero is likely to break other things down the line, not just in Better Questing. Machines in particular would likely not take well to having an stack unexpectedly self destruct (using ID for filtering purposes for example) even if, like BQ, they already checked it _was_ originally valid before hand and the subsequent code is reliant on that fact. Even simple GUIs would have issues with tooltips killing the item without the inventory container knowing causing a desync. Sure this would only happen if the NBT is missing but by the sounds of things, you're already have cases where that can and does happen.

**Comment by EweLoHD** [comment]
This makes also a JEI Plugin impossible.

**Comment by cam72cam** [comment]
Hmm, I'll take a look at implementing getDefaultInstance.  I suspect that's the root issue here

**Comment by cam72cam** [comment]
How do you recommend I should handle the situation?  An item without that metadata that's being used is invalid and has not been correctly instantiated.  There is no sane "default" value for that property.

**Comment by Funwayguy** [comment]
Can you not add pre-checks when used and if the tag is missing/invalid simply not allow it? Same way you'd check `isEmpty()` really. A user shouldn't be able to use an invalid item anyway.

Also your assumption of "correctly instantiated" pretty much comes down to "only via your mod" because almost nobody is going to know this edge case and even less will code a mod specific exception for you.

**Comment by cam72cam** [comment]
Ah ok, thanks for explaining.

3 surprises me and suggests that might be where the root of my issues/confusion lie.  I thought that my getSubItems and getCreativeTabs was implemented correctly.  I'll take some time and make sure they are functioning as expected and patch them if not (along with removing the set stack size (0)).

I might have read a bit too much into your attitude, IRL work has been nuts, sorry about that.

I'll try to get to this within the next week.
