### ISSUE TITLE
Request: Signals mod compatibility

### ISSUE THREAD

**Issue by cloakable** [cam72cam/ImmersiveRailroading#443]
Signals is a mod that adds OpenTTD style train routing to Minecraft; I'm unsure if the compatibility would be on the side of IR, TrackAPI, or Signals, but it would be a powerful expansion of IR capabilities to be able to use it to route trains.

**Comment by FriedrichLP** [comment]
Im working on a signal mod for IR. I think we wont support that mod for IR because its too much effort. My mod will to this and much more!
