### ISSUE TITLE
[1.12.2]Someone moves inside train will force nearby player teleport to the train

### ISSUE THREAD

**Issue by lordfriend** [cam72cam/ImmersiveRailroading#453]
When someone moves inside the train, anyone who near the train will be drag into that train, but then transport back. If that person does nothing, it won't change his position, if he makes a right click. he will be actually inside the train.

Here are two demo video
https://www.youtube.com/watch?v=Z2F1BEzK-dg
https://www.youtube.com/watch?v=7haLIjJ--vg

**Comment by km00700** [comment]
known issue.

**Comment by lordfriend** [comment]
Well, I didn't find an opened issue describe a similar problem.

**Comment by km00700** [comment]
Hence why I didn't close it here.
