### ISSUE TITLE
[Suggestion] Allow textures in addition to materials

### ISSUE THREAD

**Issue by DrprofLuigi** [cam72cam/ImmersiveRailroading#461]
Would it be possible to allow the use of textures for obj models rendered in-game?

i.e. if a png file is in included instead of an mtl file, it uses the texture. It would make it possible for me to make a content pack.

**Comment by fsendventd** [comment]
Lol
You got really committed on this one. I was wrong about this the whole time.

**Comment by cam72cam** [comment]
The obj spec points to a mtl using the "mtllib" directive
The mtl spec points to an image using the "map_Kd" directive

If you are using blender, make sure Path Mode: Copy is set in the obj exporter
