### ISSUE TITLE
Standardize track sizing between switches and turns

### ISSUE THREAD

**Issue by milandamen** [cam72cam/ImmersiveRailroading#467]
Switch turns and regular turns are not the same size, which makes it impossible to connect rail to it the same way.

Length: 16
Curve: 45deg
https://i.imgur.com/gzBGUuT.png

Length: 20
Curve: 45deg
https://i.imgur.com/ULIQKja.png

Length: 16
Curve: 90deg
https://i.imgur.com/d1OghzE.png

Especially the 45deg switch turns are broken. They don't line up to any normal-mode placed tracks, while the regular 45deg turns do line up with normal-placed tracks (if you discount overlap). 
Shouldn't you be able to place everything without smooth mode anyway?

**Comment by km00700** [comment]
It's a known bug that the switch size is off by one relative to the turns.

**Comment by milandamen** [comment]
This is not intuitive, and should be changed in my opinion.
