### ISSUE TITLE
Crash NullpointerException: Unexpected error

### ISSUE THREAD

**Issue by hasezoey** [cam72cam/ImmersiveRailroading#468]
crashlog: https://gist.github.com/hasezoey/a5e51d70bf5e0ccf441b2d54072aecc9
fml log: https://gist.github.com/hasezoey/05bc84cea9f946e489454637205f93a6

crashed when trying to place a (straight) road (10 blocks wide) into some tinker's consturct trees (blueprint mode)

**Comment by hasezoey** [comment]
note: after restart of Minecraft, this crash dosn't appear anymore

**Comment by cam72cam** [comment]
Fixed in 1.4.1
