### ISSUE TITLE
Book/Manual Item Instantly Crashing Game when Held

### ISSUE THREAD

**Issue by Caelharian** [cam72cam/ImmersiveRailroading#470]
Whenever I hold the Manual/Book for Immersive Railroading in my hand the game crashes. Any ideas?
All I have installed is Immersive Engineering, Immersive Railroading, In-Game Wiki Mod, JEI, OpenComputers, and Track API.

[crash-2018-11-08_22.16.22-client.txt](https://github.com/cam72cam/ImmersiveRailroading/files/2564480/crash-2018-11-08_22.16.22-client.txt)

**Comment by Caelharian** [comment]
*Update* 
When looking to 'open air' everything is fine and I can open the book.
However, the second the cross-hair makes contact with any block while holding the book the game crashes.

**Comment by cam72cam** [comment]
Thanks for the report.  I'll try to push out 1.4.1 with this and a few other fixes this weekend

**Comment by Caelharian** [comment]
Oh awesome, I figured i may be doing something wrong. I'll be looking forward to the update; no rush on my part. Thanks for the quick reply :D

**Comment by ShamblerDK** [comment]
Experiencing the same issue. I have a crash log uploaded here (too big for any of the pastebin sites):
https://mega.nz/#!ZloxiCpC!R6xKry7b-_ekN_IaT2gd8Ot1gPiP4TdQi9-EBAw52GY

**Comment by cam72cam** [comment]
I am pushing a fix later today to resolve this

**Comment by ShamblerDK** [comment]
> I am pushing a fix later today to resolve this

You are fantastic. Railcraft is never going to be updated, but it doesn't matter because your mod seems so much better :-)

**Comment by cam72cam** [comment]
Thanks!  Sorry about the crashing bug!
