### ISSUE TITLE
Stock loaded from resurce packs while in game doesn't generate 2D texture

### ISSUE THREAD

**Issue by fsendventd** [cam72cam/ImmersiveRailroading#471]
Should be self-explanatory. All stock that is loaded from a resource pack after initialization will not generate a 2D item. 
![2018-11-10_07 56 57](https://user-images.githubusercontent.com/44233145/48302805-a8b2a800-e4be-11e8-828d-a0ef11ecf2ab.png)

**Comment by cam72cam** [comment]
You will need to restart the game for that to work.  There's no way around it

**Comment by fsendventd** [comment]
Oh, OK. Thanks.
