### ISSUE TITLE
Crash when rendering Casting BP

### ISSUE THREAD

**Issue by DHunger** [cam72cam/ImmersiveRailroading#473]
When I hold the Manual in my hands and have CASTING selected, as soon as I look at the ground and the Blueprint should appear, the game crashes.

[Crash Report](https://pastebin.com/a6EGSMC3)

**Comment by fsendventd** [comment]
I think this is fixed in the latest release. Try updating.

**Comment by cam72cam** [comment]
Update to ImmersiveRailroading-1.4.1
