### ISSUE TITLE
Crash during profiling world from JER

### ISSUE THREAD

**Issue by TheSnowyChickens** [cam72cam/ImmersiveRailroading#479]
Hi,

I started the world profiling command from JER and then I got a crash.
(VanillaFix told me, that the crash should come from IR)

Crash -> [crash-2018-11-21_05.31.01-server.txt](https://github.com/cam72cam/ImmersiveRailroading/files/2602635/crash-2018-11-21_05.31.01-server.txt)

MC: 1.12.2 
IR: 1.4.1
IE: 86
T.API: 1.1_1.12  
JER: 0.8.10.50
JEI: 4.13.1.224
Forge: 2775

**Comment by cam72cam** [comment]
The crash is from IR, but that code should never be null.  I suspect a mod conflict.

**Comment by TheSnowyChickens** [comment]
Can we find out, which mod is the problematic one ?

**Comment by cam72cam** [comment]
Closed as a dupe (which was closed earlier today
