### ISSUE TITLE
Problem with trains and track blueprints

### ISSUE THREAD

**Issue by xman877** [cam72cam/ImmersiveRailroading#480]
The problem I've been having is that every time I either hold or look at either the track blueprint or a train, the screen turns blue. It's a lighter shade than the sky so its most likely not a chunk loading issue. I am still able to pause the game but no menu pops up. I've tried troubleshooting it and nothing works.

**Comment by km00700** [comment]
That light blue indicates an OpenGL Error. What graphics are you running?

**Comment by xman877** [comment]
what do you mean?

**Comment by km00700** [comment]
Graphics card

**Comment by xman877** [comment]
are you talking about my computer itself or in game?

**Comment by km00700** [comment]
computer...

**Comment by km00700** [comment]
have you set the java executable to use the NVIDIA card?

**Comment by xman877** [comment]
I'll Double check

**Comment by xman877** [comment]
Okay, I made sure that Java is using the NVIDIA card. It's still doing it...

**Comment by km00700** [comment]
can you send the "latest.log" file?

**Comment by xman877** [comment]
Wait, It turns blue when I hold the blueprint. But when I look at stuff its fine. So that a start. I"ll try and get you the log file.

**Comment by xman877** [comment]
https://paste.ubuntu.com/p/RBkdYS7SyN/

Here's the log. Idk if it will be much help but here it is.
Its late where i'm at right now so this is my last comment for the night.

**Comment by cam72cam** [comment]
It's still using your Intel card.

Also props for using Ubuntu :+1:

**Comment by Larky2k** [comment]
If you go into your BIOS you can disable the Intel graphics.

**Comment by xman877** [comment]
Now I have another problem, now my Minecraft won’t open. Every time I try to open immersive railroading, it just crashes before I even got to the Mojang screen

**Comment by xman877** [comment]
Says that the driver doesn’t support OpenGL

**Comment by cam72cam** [comment]
You will need to update your nvidia driver

**Comment by xman877** [comment]
Alright I updated the Nvidia drivers, it makes it past the launcher but now the problem is that when it gets to the mojang screen it stops responding, but it’s not OpenGL. So I’ll see what I can do.

**Comment by xman877** [comment]
Alright! I finally got it working!! Thank you all so much for your help!
