### ISSUE TITLE
Switch inconsistent redstone interaction

### ISSUE THREAD

**Issue by DHunger** [cam72cam/ImmersiveRailroading#482]
[Image](https://imgur.com/a/v7Js8Tw)

I found an Issue with using switches starting at an angle,

as visible in the Picture above, the blocks, from which the switch is controllable is not at all consistent, in case of the third exampel this even leads to impossible controlling, since that spot would be covered by another rail coming in.

My idea would be to do it, so that the whole switch (or at least most of it) react to redstone and switch accordingly, or at least prevent something like that in the third example from happening.

**Comment by bplainia** [comment]
It consistently is centered around the origin of the track. An improvement for this is currently in testing.
