### ISSUE TITLE
sound and overheating

### ISSUE THREAD

**Issue by quentfr21** [cam72cam/ImmersiveRailroading#483]
hello

i disable the diesel overheat after that when the locomotive reach the max temp, sound of track and loco no more working (maybe also horn)

thanks

**Comment by cam72cam** [comment]
@FriedrichLP we need to look into this

**Comment by km00700** [comment]
I know there are issues with sound due to base mod changes in resource locations. Legend, if you see this, please commit your changes to a branch, instead of master.

**Comment by km00700** [comment]
although this seems like the diesels are still locking out despite not having max temp set to lock them out.

**Comment by quentfr21** [comment]
hello 

it's my mistake i change config only server side, now with client side config modified it's work fine 

sorry

**Comment by cam72cam** [comment]
No worries, glad it was not a serious bug
