### ISSUE TITLE
Help please - can't edit inventories when in a train

### ISSUE THREAD

**Issue by Gilmania** [cam72cam/ImmersiveRailroading#484]
I love the idea of this mod but I haven't been able to use it effectively thus far because of a recurring bug.  When I try to edit the inventories of locomotives (tried now on both A1 Peppercorn & K4 Pacific) from the cab (i.e. when riding in it or when sneak clicking the cab) the GUI totally glitches and prevents me from adding anything (i.e. water and coal).  If I attempt to pick up an item it either immediately places it back down, picks up a different item in my inventory, or allows me to place in the locomotive inventory but doesn't actually transfer (i.e. when attempting to transfer an entire item stack to the locomotive it will move in the GUI but then closing the GUI & re-opening yields that the item is back in my inventory).  Essentially there is no way to edit the inventory of the locomotive from the cab.  Occasionally when restarting the server the cab will have fallen off of the placed locomotive as a floating item, that I then have to place back on frame, but this isn't always the case.  Note that this error doesn't happen at all when accessing the locomotive's inventory by sneak clicking something closer to the front of the machine (such as one of the boilers).  So I can get fuel & water in but would need to stop and get out of the locomotive to do so.  Successfully changing the inventory in this way does NOT cause visualized changes in the GUI when accessed from the cab - it's as if the cab itself is completely glitching (except that I can control throttle etc).

I've tried restarting my game, the server (a small one I manage and play with my wife in our house), and removing & replacing the locomotive all without change.

Thanks for any help.

I'm using mod version 1.3.3.

**Comment by Gilmania** [comment]
It seems to be doing something similar with a tender I've now attached.  I have the issue when attempting to open the inventory GUI from the back end but not from the side near the front.

**Comment by cam72cam** [comment]
Can you upload a video showing this?

**Comment by Gilmania** [comment]
Video can be found here:
https://youtu.be/y3PnBYCd03c

List of mods I use:
AppleCore
Backpacks!
Baubles
BinnieCore
Binnie'sExtraBees
Binnie'sExtraTrees
Binnie'sGenetics
BiomesOPlenty
Buildcraft
Chameleon
ChickenChunks
CodeChickenLib
CTM
Decocraft
Dr.Zhark'sCustomSpawner
Dr.Zhark'sMoCreatures
Forestry
GalacticCraftCore
HungerOverhaul
ImmersiveRailroading
IndustrialCraft2
InventoryTweaks
JourneyMap
JustEnoughItems
LunatriusCore
MagicBees
MicDoodle8 Core
MobController
Mystcraft
Pam's HarvestCraft
ptrmodellib
Schematica
StorageDrawers
StorageDrawers Extras
Thaumcraft
The Spice of Life
Track API
Waila

**Comment by cam72cam** [comment]
Ok, it looks like whatever mod is changing how your inventory works is conflicting with IR.

Also, trains hitboxes are sometimes funny until they are moved once (known issue)

**Comment by Gilmania** [comment]
Ya that’s what I thought initially so I took out inventory tweaks and JEI but it didn’t help. Haven’t tried Backpacks! yet. Doesn’t change if you move the trains and doesn’t happen on other parts of the vehicles outside of the rear end.

**Comment by cam72cam** [comment]
Do you have a link to your pack?

**Comment by Gilmania** [comment]
I don’t use a mod pack. The backpack mod I use is here:

https://minecraft.curseforge.com/projects/backpacks

**Comment by cam72cam** [comment]
Closing as a mod conflict
