### ISSUE TITLE
More efficient sound management

### ISSUE THREAD

**Issue by DHunger** [cam72cam/ImmersiveRailroading#488]
While playing a modpack with open computers and immersive railroading, i found out, that with immerive railroading activated, the computer.beep function from OC only plays the noteblock sound, but without the mod, the "real" beep sound plays. Based on [this issue](https://github.com/MightyPirates/OpenComputers/issues/1023) i assume, that immersive railroading fills up all (or at least most) of the available sound memory, so that other mods (like OC or computronics ([see here](https://github.com/Vexatos/Computronics/issues/166)) as well) have no more space to use it. 

Would it be possible to improve sound management, so that sounds are only loaded when needed and therefor keeping memory usage low?

**Comment by cam72cam** [comment]
This should have been fixed a few versions back, what version are you running?

**Comment by DHunger** [comment]
1.4.1, but i never tested with older versions

**Comment by DHunger** [comment]
with overrideSoundChannels disabled, it seems to work
