### ISSUE TITLE
Question about non-destructively implementing a user-made 1m track model

### ISSUE THREAD

**Issue by Electrostasy** [cam72cam/ImmersiveRailroading#492]
I wanted to try a different track model that is more visually appealing to me personally, but have run into a couple issues that I thought someone here could point me in the right direction.

I made a custom model with the same dimensions as track_1m.obj and track_1m_model.obj in `\assets\immersiverailroading\models\block\`, however I could not get it to load in-game via resource packs (tracks show up as default tracks do) and had to drag and drop into the mod .jar file (hence "non-destructively" in the title).

I ensured that the .obj files use the provided .mtl files and that my 128x128 UV map is named prototype_texture.png (otherwise there'd be crashing and other rendering issues), but only curved tracks render properly. Straight tracks are completely invisible, same goes for the straight section of switch tracks, of which the curved sections render properly (toggling them with a lever also reveals more of the curved track).

10m curved tracks of each angle:
![2018-12-01_19 35 20](https://user-images.githubusercontent.com/44975313/49331120-330f9880-f5a1-11e8-984f-920da84ba792.png)

Switch track with redstone off:
![2018-12-01_19 37 10](https://user-images.githubusercontent.com/44975313/49331138-74a04380-f5a1-11e8-88c0-cb7d7fff2fcc.png)

Switch track with redstone on:
![2018-12-01_19 37 23](https://user-images.githubusercontent.com/44975313/49331150-808c0580-f5a1-11e8-92eb-a19eba086cfb.png)

Straight track is invisible (same applies to sloped tracks):
![2018-12-01_19 37 36](https://user-images.githubusercontent.com/44975313/49331158-9699c600-f5a1-11e8-9604-bd71af08fc64.png)

Please look away from the amount of space I'm wasting in my UV map:
![maya](https://user-images.githubusercontent.com/44975313/49331192-fd1ee400-f5a1-11e8-8fb8-b3d9902af0a9.png)

Just to be sure I also tried running Minecraft with only Immersive Engineering, Immersive Railroading, TrackAPI and yielded the same results.

Is this currently possible to do, is there a better way, or am I missing something here? Thanks.

**Comment by cam72cam** [comment]
The key is that you need the groups named the same thing.  I break apart the model by group name in order to render the track.

I'll be adding support for custom resource pack tracks later on
