### ISSUE TITLE
Some small improvement which can help in a survival server

### ISSUE THREAD

**Issue by lordfriend** [cam72cam/ImmersiveRailroading#497]
- Track Blueprint can automatically place blocks under track (rail bed fill) which is great but not enough. One improvement I wish is player can define the thickness and wideness of the rail bed fill. this can let survival player have a chance to build railway even they don't have worldedit permission. 

- UI of casting basin have two many items which sometimes will use up graphics card memory. my friend which use a MacBook always has trouble to use casting basin. I think it's because the UI just load all textures of trains in a single page. if a pager can be added and load only one page of the textures, it will significantly reduce the memory usage.  This also solves the problem when many resourcepack loaded I must scale UI to show all the items.

- make the track harder to break or can only be break by certain tools. Reduce the chance new player accidentally destroys a track.

**Comment by lordfriend** [comment]
@Larky2k Thank you for the second config option. I'll let my friend try this.

For the first, the purpose is to build a more realistic bridge or fill road bed which usually done by worldedit, for some curve or lean road, even a mathematical formula is needed to create a non-regular shape. If Track Blueprint can place some blocks underlying the railway it would save a lot of time to build the road.

**Comment by Larky2k** [comment]
It does lay blocks when placeing over a gap

**Comment by lordfriend** [comment]
I mean hope the blocks laid by track blueprint thicker and wider (not 3 blocks wide but 5)

**Comment by km00700** [comment]
Good Lord, imagine the griefing opportunities!

**Comment by lordfriend** [comment]
I don't think this will have any effects on griefing opportunities, track blueprint will not generate blocks if they are already there. set 25 blocks wide will also require more blocks inside the player's inventory.
