### ISSUE TITLE
Rain passes through the locomotives

### ISSUE THREAD

**Issue by Senyum** [cam72cam/ImmersiveRailroading#499]
Rain passes through the locomotives.
Immersive Railroading version 1.4.1_1.12.jar
Minecraft 1.12.2
Forge 2768
![rain_bug](https://user-images.githubusercontent.com/36424845/50054136-1c944000-0150-11e9-97e9-01abbe33460f.png)

**Comment by cam72cam** [comment]
This can be "fixed" by setting shaderFriendlyRender to false.

There is no good way to solve this when rendering as a normal entity in minecraft as far as I am aware
