### ISSUE TITLE
Add signals and ATS

### ISSUE THREAD

**Issue by gaojie429** [cam72cam/ImmersiveRailroading#507]
I am playing this mod on multiplayer, and sometimes we have an accident when my friends are stopping at the station which I am heading for because we have no means to confirm wheather the train exists forward.
So, I want you to add some signals and ATS like used in Japan.

**Comment by Larky2k** [comment]
Already planned, quick search on the discord channel would of answered your question. If not on discord link is on main page.

**Comment by WrongWeekend** [comment]
Signals can already be improvised using detector augments connected to any sort of redstone powered light (such as a redstone lamp) or other output device.

**Comment by cam72cam** [comment]
This is being added in IR addons: see https://minecraft.curseforge.com/projects/traffic-control as an example
