### ISSUE TITLE
Add a "OpenComputers" mode to the detector augment

### ISSUE THREAD

**Issue by LizzyTrickster** [cam72cam/ImmersiveRailroading#509]
Would it be possible to get a mode for the detector augment similar to the locomotive control's OC mode?

Currently when using the detector for OC it still emits a redstone signal which can activate nearby switch track if too close and causes trains to be split.

**Comment by andrboot** [comment]
Hi Lizzy,
You can use the OC Augment for detection :) Just set it up as a event handler.
See my tag-OC detector for a 'simple' example :) 
https://github.com/andrboot/ImmersiveRailroading-Auto-Scripts/blob/master/opencomputers.tagdetect.lua

**Comment by LizzyTrickster** [comment]
That's what i'm doing, but the issue is that the detector still emits redstone signals when locos pass over it which triggers switch tracks

**Comment by cam72cam** [comment]
Right click on the augment with a redstone torch.  It will change modes

**Comment by LizzyTrickster** [comment]
I know it changes the mods, but the issue is that all the current modes (at least in IR 1.4.1 for mc 1.12) will output a redstone signal in some fashion.

A way I've just worked out to get around this is to set the detector to "stock" mode and told it to only match hand cars. It would still be nice to have a "No Redstone" mode for when exclusive use by OC computers is wanted.

**Comment by cam72cam** [comment]
Ah, my mistake.  I thought I had added that at some point. I'll try to include it in the next release

**Comment by LizzyTrickster** [comment]
Update: The setting of the detector to only match hand cars also affects the computer detection so that solution wont work :/

**Comment by cam72cam** [comment]
You can try the test build here, the track system is still slightly in flux so you may see some issues before the next release: http://174.138.127.16/job/Immersive%20Railroading/384/artifact/build/libs/ImmersiveRailroading-1.4.1_1.12-384.jar
