### ISSUE TITLE
Investigate Jerky Movement

### ISSUE THREAD

**Issue by cam72cam** [cam72cam/ImmersiveRailroading#51]
Sometimes client side the entities move smoothely, sometimes they are jerky.  Most of the time this is mixed.

**Comment by DonBruce64** [comment]
Question: are these jerks sporadic or constant?  Like do they occur every movement update or do they happen once and a while?  Also, does this happen when in the locomotive?  I've encountered odd jerks before in movement, but the cause depends on when it's occurring.

**Comment by cam72cam** [comment]
Fixed in the netcode rewrite
