### ISSUE TITLE
Bell Sound

### ISSUE THREAD

**Issue by CSX8600** [cam72cam/ImmersiveRailroading#519]
The horn is great and all, but there are several situations where ringing the bell on the locomotive is preferred (such as moving through a yard, moving past men & equipment, no-horn zones, etc.).  Any way you would be able to add a nice (realistic) sounding bell to locomotives?

**Comment by Larky2k** [comment]
Already done

**Comment by CSX8600** [comment]
Is that in the most recent version?  Maybe I missed the key for it...

**Comment by Larky2k** [comment]
it hasn't been released yet
