### ISSUE TITLE
MBBlueprintRender error

### ISSUE THREAD

**Issue by twenty41** [cam72cam/ImmersiveRailroading#521]
Friend is crashing in multiplayer with an error related to blueprints. Crash log attached
[crash-2019-01-07_08.04.09-client.txt](https://github.com/cam72cam/ImmersiveRailroading/files/2732845/crash-2019-01-07_08.04.09-client.txt)

**Comment by cam72cam** [comment]
Please upgrade to 1.4.1 or 1.5.0 as this bug has already been fixed in those version.

**Comment by twenty41** [comment]
this doesn’t seem to be the case, attempted it on the latest build. soon after he crafted the blueprint, his screen turned white and his game crashed, attempted a few times. ended up having to remove the mod

**Comment by Larky2k** [comment]
What's your mates specs and how much RAM allocated to MC?

**Comment by cam72cam** [comment]
@twenty41 please attache the crash log of trying with the latest version

**Comment by twenty41** [comment]
the previously attached crash log was last night, so still the latest build. working on getting his specs right now. i’m on mobile, hope i’m replying to your comments correctly

**Comment by Larky2k** [comment]
Your not on latest build according to crash lot at top.
