### ISSUE TITLE
Japanese Translation Update

### ISSUE THREAD

**Issue by gaojie429** [cam72cam/ImmersiveRailroading#522]
Hi, I added some name of new item and message to my Japanese translation file, and modified some unnatural translation.
Could you update this lang file on the next version?
[ja_JP.lang.zip](https://github.com/cam72cam/ImmersiveRailroading/files/2733705/ja_JP.lang.zip)

**Comment by FriedrichLP** [comment]
Of course!

**Comment by FriedrichLP** [comment]
I updated the file in the repository. Thank you again for your work!
