### ISSUE TITLE
cannot place tracks IR 1.5.0_1.12-402

### ISSUE THREAD

**Issue by ghost983** [cam72cam/ImmersiveRailroading#528]
Hi im running my own server for myself and a friend of mine who is very much a train fanatic in every sense of the word, so i decided to grab this mod for us to use. now, on single player the mod runs fine and as intended. however when i run the mod in my server it will not allow me to place down tracks and if i enter the configuration screen for the track, when i exit that screen the tracks become giant/oversized. this also happens when placing and using the conveyors from the in game manual, when placed they are giant sized. I am running the server off of minecraft 1.12.2-14.23.5.2768 and FORGE.

**Comment by cam72cam** [comment]
Hi there, could you upload some screenshots?

**Comment by ghost983** [comment]
sorry. i think it was either just a bug/glitch with the server or perhaps it didnt like one of my other mods. i went through and re-did my server files and redownloaded and placed the mod and everything seems to be working fine now. it tells me what materials i need to craft now{it didnt before), it lets me place tracks and that weird graphical glitch of some items being oversized is fixed as well. probably just a one time thing. i was surprised by how fast you responded honestly, im pretty new to the minecraft mod community and you dont get that kind of response with other communities. so thanks a ton. :) i enjoy your mod and really appreciate it.

**Comment by cam72cam** [comment]
:+1:
