### ISSUE TITLE
Crash on Startup

### ISSUE THREAD

**Issue by GreatCow** [cam72cam/ImmersiveRailroading#548]
My game crashes when starting MC on Uploading IR Textures" and pops 'Error: java.lang.OutOfMemoryError: Java heap space'.  Crash Report: https://pastebin.com/DkRNQxNm

Crashes on this: https://gyazo.com/6807dbef7f350d6cd474db4d0714a201
Error: https://gyazo.com/6c20b831a94d466b02e50c526e83bcfa

I have 11G Ram assigned and only IR and TrackAPI in my mods folder.

**Comment by Larky2k** [comment]
NEVER allocate all your system RAM drop it down to 6Gb for MC

**Comment by GreatCow** [comment]
I've got 32G on my system so that shouldn't be it.

Also didn't help.

**Comment by Larky2k** [comment]
update java your using a very old java

**Comment by GreatCow** [comment]
Nope.
New Crash Report (JIC): https://pastebin.com/CrWHjme9

**Comment by Larky2k** [comment]
Still using old Java, point MC to new Java

**Comment by GreatCow** [comment]
Still no cheese.

https://pastebin.com/iq7pfhjJ

**Comment by Larky2k** [comment]
Only other things I can think of is drop down a forge version and update graphics drivers.

**Comment by GreatCow** [comment]
Still ain't working. But thanks for the help.

Its just weird as it was starting fine last night but I just tried to start it up today and it wouldn't.

**Comment by Larky2k** [comment]
Try to look up arguments for Java garbage collection and see if that helps.

**Comment by GreatCow** [comment]
Just Reinstalling MC fixed it. Should of tried this earlier.
