### ISSUE TITLE
Concrete Ties

### ISSUE THREAD

**Issue by Astewen** [cam72cam/ImmersiveRailroading#554]
I searched issues open and closed and didn't see this...

At some point could we have concrete ties in addition to the creosote ones? I'd like my mainlines to use the more modern concrete ones and branches use the order wooden ones (more like US prototype).

Thanks for the consideration.

**Comment by km00700** [comment]
this falls under multiple track types

**Comment by bigyihsuan** [comment]
Sounds perhaps easy to do, just make a new texture, an option in the track GUI to switch between tie types, and have it use a different block instead.

With that new build with the quick-switching of rail bed block, that should also apply here, but for rail ties.

**Comment by km00700** [comment]
Rail bed works differently from the model loader, so it's not a case of "Just do X".
