### ISSUE TITLE
possibly add these 2 logos the EBT logo for the NG goldola and the CNJ logo for std gauge hoppers

### ISSUE THREAD

**Issue by Comet051091** [cam72cam/ImmersiveRailroading#560]
here are the 2 logos i'd like to see 
![image](https://user-images.githubusercontent.com/48610435/54470121-06127a80-4779-11e9-94fd-5be0ce1c2e7c.png) this is the 1 for the sg hoppers

![image](https://user-images.githubusercontent.com/48610435/54470127-1296d300-4779-11e9-9f6f-76a5997d42d9.png) and this is for the ng gondola

please add these if possible thanks

**Comment by Thomas4peyton** [comment]
I'm certainly not going to put the second one on my base game model; which I might add is due to be replaced shortly.  Sorry.  :^3
