### ISSUE TITLE
Major FPS Drops

### ISSUE THREAD

**Issue by Komplein** [cam72cam/ImmersiveRailroading#563]
Clean map. Last forge last ir. Have same issue on clean world, clean modpack. Unknown entity spawn on bedrock level. Invisible.
![Безымянный](https://user-images.githubusercontent.com/44989505/54814682-47d38180-4ca1-11e9-8f82-c7cdc7acc94c.png)

**Comment by km00700** [comment]
That's the IR MagicEntity. It forces pretty much anything from IR in the world to render. It's supposed to be there. What are your system specs? That can be a much bigger factor.

**Comment by Komplein** [comment]
> That's the IR MagicEntity. It forces pretty much anything from IR in the world to render. It's supposed to be there. What are your system specs? That can be a much bigger factor.

i5-4690k 3,5 GHz 16GB RAM GTX1060. Maybe optifine issue?

**Comment by km00700** [comment]
Possibly, certain settings on Optifine mess with IR. Just curious, which IR resource packs do you have installed?

**Comment by Komplein** [comment]
Narrow Gauge Goddies only

**Comment by km00700** [comment]
Are the FPS drops random?

**Comment by Komplein** [comment]
> Are the FPS drops random?

Yep. Entity sometimes dissapear (or going down in list), and drops with him) I'll try to launch withot optifine and send reply.

**Comment by Komplein** [comment]
That was optifine issue. Thank you for anwsers. I'm just deleted optifine, and all fine. ^^
