### ISSUE TITLE
JER profiling crash

### ISSUE THREAD

**Issue by genthug** [cam72cam/ImmersiveRailroading#565]
I realize there is an issue already out on this, however it is now 4 months old and no update has been given on it. This issue was also brought up recently over on [JER's GIT.](https://github.com/way2muchnoise/JustEnoughResources/issues/173) I'm getting crashes which are pointing to IR when attempting to fully profile a world with JER. [Crash Log](https://paste.dimdev.org/oboyawanar.mccrash)

**Comment by Larky2k** [comment]
Update your java to start with, this will save you bothering IE when that starts crashing the game.

**Comment by genthug** [comment]
Using the latest JER alpha build + forcing Twitch to use a custom Java install does work. Just wish there was a way on Twitch to force it to use it 100% of the time... and I wish that Twitch would keep Java updated as well.

Thanks Larky. Now I just need to go talk to JER about the fact that I can't actually see the ore gen on the latest Alpha.

**Comment by genthug** [comment]
My apologies, I lied. Issue persists on latest alpha with a custom Java install running. Got lucky with it once and thought the issue was solved. Has now crashed 3 out of 4 times. [New crash log](https://paste.dimdev.org/irevanadox.mccrash)
