### ISSUE TITLE
Request: Cattle car

### ISSUE THREAD

**Issue by HighSeasCaeser** [cam72cam/ImmersiveRailroading#57]
Add a cattle car -- can handle entities  (cows sheep, mobs?)

add a multi block to support the loading and unloading of said entities.

**Comment by cam72cam** [comment]
I'll be doing the code in https://github.com/cam72cam/ImmersiveRailroading/issues/218

**Comment by cam72cam** [comment]
This has been modeled and is in game.  Code support TODO
