### ISSUE TITLE
Resourcepacks automaticly eject when changing shaders

### ISSUE THREAD

**Issue by Excited-Naive** [cam72cam/ImmersiveRailroading#571]
1. Load IR resourcepack
2. Load a shader
3. Close the shader
4. Resoursepacks all eject out and cannot be load back until restart the game.

**Comment by FriedrichLP** [comment]
That's not an issue of IR. Minecraft has a protection for when your memoy usage is too high. Once this is the case it automatically ejects all resourcepacks to free some of that precios memory.
