### ISSUE TITLE
Minecraft is stopping working when I start the engine of diesel locomotive(it's not a crash, a crash report is not creating)

### ISSUE THREAD

**Issue by alt2m** [cam72cam/ImmersiveRailroading#583]
I have only a console log: https://paste.ee/p/fD6N3

**Comment by km00700** [comment]
That's above a java crash. Something in your system is causing the crash. From what it seems, there might be a corrupted audio codec.

**Comment by km00700** [comment]
Also, you have an out of memory exit code, so something is causing memory usage to spike critically higher than 6GB. How much RAM does your entire system have?

**Comment by alt2m** [comment]
> Also, you have an out of memory exit code, so something is causing memory usage to spike critically higher than 6GB. How much RAM does your entire system have?

8GB

**Comment by alt2m** [comment]
UPD.
This happens only with locomotives from other resource packs.
