### ISSUE TITLE
Add monorail switch function

### ISSUE THREAD

**Issue by Excited-Naive** [cam72cam/ImmersiveRailroading#586]
Samples:
https://youtu.be/wsrlw2cm-jc monorail
https://youtu.be/WZ_PdCgz7ik maglev

**Comment by km00700** [comment]
This isn't Immersive Monorailing.
Adding that function would require us to rewrite the animation code for limited set of cases. 
If cam does decide to implement support for this, it would come after electrics.

**Comment by CyberJack100000** [comment]
Adding this feature soon™️

**Comment by CyberJack100000** [comment]
Withing this week

**Comment by CyberJack100000** [comment]
@Excited-Naive @km00700 you're welcome
