### ISSUE TITLE
Crash while loading models (threading)

### ISSUE THREAD

**Issue by Frontrider** [cam72cam/ImmersiveRailroading#587]
This is the crash that I get, when trying to run the game with the mod installed.

https://paste.ee/p/BAUtV

**Comment by Larky2k** [comment]
Need a crash report

**Comment by hayesj1** [comment]
Looks like Bloodmagic crashed, not IR

**Comment by Frontrider** [comment]
This is the only report I have.
the last thing that happens, that is visible on the gui (it shows up in the progressbar):
`[17:48:52] [Client thread/INFO] [immersiverailroading]: rolling_stock/locomotives/a1_peppercorn.json`
If you can tell me what that xcb is, than we can move forward.

**Comment by cam72cam** [comment]
XCB is a library on your linux system that java uses to interact with the X11 windowing system

```
[17:45:05] [Sound Library Loader/INFO] [minecraft/SoundManager]: Starting up SoundSystem...
[17:45:05] [Client thread/ERROR] [minecraft/Minecraft]: ########## GL ERROR ##########
[17:45:05] [Client thread/ERROR] [minecraft/Minecraft]: @ Pre startup
[17:45:05] [Client thread/ERROR] [minecraft/Minecraft]: 1281: Invalid value
```

That happens before it gets into IR so it looks like you gpu driver should be updated or your XCB/X11 libraries.

**Comment by Frontrider** [comment]
The forge loading screen was the problem.
