### ISSUE TITLE
Rails Won't Place On Some Blocks in 1.12.2

### ISSUE THREAD

**Issue by redstone2019** [cam72cam/ImmersiveRailroading#596]
#### 

**They won't place down on top of these blocks**:
**§** Anvil, Beacon, Beds, Brewing Stand, Buttons, Cake, Carpets, Cauldron, Chest, Cobblestone Wall, Daylight Sensor, Doors, Dragon Egg, Enchanting Table,  Ender Chest, End Rod, End Portal, Farmland, Fences, Fence Gates, Glass, Glass Panes, Glowstone, Ice, Iron Bars, Ladders, Lever, Nether Brick Fence, Pressure Plates, Rails (Vanilla), Redstone Comparator, Redstone Dust, Redstone Repeater, Redstone Torch, Sea Lantern, Signs, Shulker Box, Slabs (Bottom Half), Torch, Trapdoors, and Trapped Chest **§**

![Inked2019-05-10_21 45 24_LI](https://user-images.githubusercontent.com/50508889/57565179-99c58900-736d-11e9-8a7b-bdaec03bd452.jpg)

You need to break the blocks yourself before placing the track blueprints down.

![Inked2019-05-10_21 50 57_LI](https://user-images.githubusercontent.com/50508889/57565206-50296e00-736e-11e9-9466-a5feebd63ece.jpg)
![Inked2019-05-10_21 51 02_LI](https://user-images.githubusercontent.com/50508889/57565207-50296e00-736e-11e9-96ca-f98f77c3c5fe.jpg)
![Inked2019-05-10_21 51 04_LI](https://user-images.githubusercontent.com/50508889/57565208-50c20480-736e-11e9-820e-a7cdc2fd22cf.jpg)

**If this issue is not fixable please reply that.**

**Comment by km00700** [comment]
This is not a bug. Rails, intentionally will not place on top of transparent blocks.

**Comment by redstone2019** [comment]
Ok, thanks. 😮

**Comment by redstone2019** [comment]
Close #596

**Comment by redstone2019** [comment]
Fixes #596

**Comment by redstone2019** [comment]
redstone2019/ImmersiveRailroading#596

**Comment by jasonballinger** [comment]
@redstone2019 BRUH moment lol
