### ISSUE TITLE
Linear acceleration and VVVF sound

### ISSUE THREAD

**Issue by Excited-Naive** [cam72cam/ImmersiveRailroading#603]
These functions are all for upcoming electric update. Most of electric trains uses Linear acceleration and have VVVF sound. 
And btw if openable doors can come with that, I'm sure there will be more passenger car add-on packs.

**Comment by Excited-Naive** [comment]
And RTM will be totally trash? Almost LMAO

**Comment by cam72cam** [comment]
What is this ticket?
