### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Rockefeller157** [cam72cam/ImmersiveRailroading#604]
Hello.

I have a modded server in 1.12.2, with immersive railroading.
Everything worked fine on the server, I was testing that everything worked. But, right after I took the mod's guide, the game crashed, as shown in this crash report and this log file.

Crash report:
https://pastebin.com/nqjxrxTb

Log:
https://pastebin.com/u9TvwxJw

Forge version:
1.12.2 - 14.23.4.2760

Thanks for your time and your help.

**Comment by cam72cam** [comment]
Upgrade immersiverailoading to 1.6.1
