### ISSUE TITLE
Support IC2 creosote oil or Mekanism gas?

### ISSUE THREAD

**Issue by polyzium** [cam72cam/ImmersiveRailroading#605]
I don't have Thermal Expansion or Immersive Engineering/Petroleum installed, and thus I can't power diesel engines with the mods I have.

**Comment by km00700** [comment]
In the immersive railroading config, you can define anything you want as a fuel. You just need the forge fluid name for it.

**Comment by km00700** [comment]
<img width="301" alt="Screen Shot 2019-06-03 at 12 47 49 PM" src="https://user-images.githubusercontent.com/19310181/58829901-d3e91a00-85fd-11e9-8f13-196794535dfb.png">

**Comment by polyzium** [comment]
And the numbers are what? Burning rate (mB/t)?

**Comment by km00700** [comment]
It's a burn time. (t/mB) Anywhere from 150-170 should be fine for mek. gas. I'd personally put creosote down near 100-110.

**Comment by polyzium** [comment]
Alright, thank you for the explanation, closing
