### ISSUE TITLE
Locomotives are rendered wrongly?

### ISSUE THREAD

**Issue by Flow86** [cam72cam/ImmersiveRailroading#629]
Hi,

I'm using 

ImmersiveRailroading-1.6.1_1.12-1138

My locomotive seems to be incomplete:

![2019-07-26_09 02 36](https://user-images.githubusercontent.com/656249/61932650-34546200-af84-11e9-8c30-a569705beba0.png)

Whats wrong here - do I miss a part of the locomotive, or does my minecraft not render it?

Im using:

Forge Version 14.23.5.2815
OptiFine_1.12.2_HD_U_E3.jar

I first thought its a shader bug or something like that, but it still gets rendered like that?
Is it incompatible with optifine? but why do I find videos of IR with shaders and optifine then on youtube?

Thank you for your help

**Comment by km00700** [comment]
What graphics card do you have on your computer? Also, try enabling shaderFriendlyRender in the IR graphics config file.

**Comment by Flow86** [comment]
it's a nvidia 1080Ti (newest geforce driver)

**Comment by Flow86** [comment]
useShaderFriendlyRender is already true

**Comment by km00700** [comment]
And Java is set to use it? Try disabling shaderFriendlyRender and disable VBOs in MC config. If that fails, try without Optifine as certain versions of Optifine Ultra don't play nicely with IR graphics.

**Comment by Flow86** [comment]
> And Java is set to use it?

what do you mean by that?

VBOs are off.

Same thing without optifine.

Well - there is no "hull" item for the locomotive - is it? (ge b40-8w) - not that I simply missed some items?

**Comment by km00700** [comment]
With Nvidia cards, you need to use the Nvidia control panel to use the High performance card on for the javaw.exe executable.

**Comment by Flow86** [comment]
ah yes, thats already set

**Comment by km00700** [comment]
Are you able to drive the locomotive? What does it say when you right-click on it with a wrench.

**Comment by Flow86** [comment]
ah - i simply did not build the top "shell" - I always "mounted" the locomotive - right clicking with a wrench it tells me "Missing: ..." 

Oh man .. ;-) Sometimes the "Bug" is in front of the computer. 

I think there's a wiki entry missing about how to assemble a rail car :-D

Thank you for helping me. Without that I never have figured it out :+1:

**Comment by km00700** [comment]
Classic PEBCAK.

**Comment by Flow86** [comment]
definitly :+1:
