### ISSUE TITLE
locomotive not accepting fuel or water

### ISSUE THREAD

**Issue by therealbdld** [cam72cam/ImmersiveRailroading#634]
the Peppercorn loco will not accept fuel or water it glitches out my whole inventory

**Comment by cam72cam** [comment]
Can you include a screenshot or more info?

**Comment by TrainLord** [comment]
I'm having the same problem but only one engine is accepting feul or water but the rest won't

![2019-09-04_08 38 39](https://user-images.githubusercontent.com/50807961/64259843-765fb480-ceef-11e9-99f0-8910b22bb8a2.png)

**Comment by Larky2k** [comment]
How much RAM have you got allocated to MC

**Comment by TrainLord** [comment]
idk but it worked fine last time i used it

**Comment by TrainLord** [comment]
and i deleted the mod and redownloaded it but that didnt help

**Comment by TrainLord** [comment]
![Capture](https://user-images.githubusercontent.com/50807961/64280528-ef263700-cf16-11e9-8d4d-c6504ee23552.PNG)
here is my ram info

**Comment by Larky2k** [comment]
So how much is allocated to MC

**Comment by TrainLord** [comment]
I don't know how do i see that?

**Comment by Larky2k** [comment]
What's the number above the main loading bar of forge when loading or in-game press F3 and look top right corner

**Comment by TrainLord** [comment]
ok let me get back in the game

**Comment by TrainLord** [comment]
![2019-09-04_13 34 16](https://user-images.githubusercontent.com/50807961/64281422-b5eec680-cf18-11e9-8d6b-678c7e05bab5.png)

**Comment by Larky2k** [comment]
You dont have enough RAM allocated, increase to 3gb, install foamfix, Optifine, BetterFPS, turn everything to low and turn on IconCache in the IRconfig,

**Comment by TrainLord** [comment]
how do i turn everything to low

**Comment by TrainLord** [comment]
the graphics

**Comment by Larky2k** [comment]
You need Optifine as a mod and it's in settings

**Comment by TrainLord** [comment]
ok thanks

**Comment by TrainLord** [comment]
didn't help i have optifine

**Comment by Larky2k** [comment]
Have you done everything I said to do

**Comment by TrainLord** [comment]
i got optifine

**Comment by TrainLord** [comment]
im just trying to turn everything to low

**Comment by Larky2k** [comment]
You need to do everything I said to do

**Comment by TrainLord** [comment]
ok

**Comment by TrainLord** [comment]
i will do that thanks for the help

**Comment by TrainLord** [comment]
i got all the mods but it still wont work

**Comment by cam72cam** [comment]
@Larky2k sent you down the wrong path.

What IR version are you running?  Are there any errors in the logs?

**Comment by TrainLord** [comment]
no im running the latest one

**Comment by TrainLord** [comment]
it was
ImmersiveRailroading-1.6.1_1.12-1138

**Comment by TrainLord** [comment]
is that the right one

**Comment by TrainLord** [comment]
![2019-09-04_08 38 39](https://user-images.githubusercontent.com/50807961/64302212-e7cb5180-cf47-11e9-908d-399a50ad13fd.png)

**Comment by cam72cam** [comment]
Can you upload your latest.log file? something odd is going on

**Comment by TrainLord** [comment]
ok
[latest.log](https://github.com/cam72cam/ImmersiveRailroading/files/3577007/latest.log)

**Comment by cam72cam** [comment]
What resource packs / mods do you have?  I am seeing some weird errors in the logs.

**Comment by TrainLord** [comment]
i have better fps foam fix optifine IE (immersive engineering) Track api IR
and i have a resorce pack that adds extra steam engines
but its been doing that since i got the mod the fuel problem

**Comment by TrainLord** [comment]
i mean when i got the mod it was having problems with the fuel

**Comment by cam72cam** [comment]
Try removing the resource pack that adds extra steam engines, I think it might be bugged.

**Comment by TrainLord** [comment]
no its not that the whole mod is doing the fuel glitch

**Comment by cam72cam** [comment]
Remove that resource pack.  It is throwing errors which might be breaking stuff.

**Comment by TrainLord** [comment]
ok

**Comment by TrainLord** [comment]
i removed the pack and the mod is still not working right

**Comment by TrainLord** [comment]
im deleting the mod and not using it untill that gets fixed

**Comment by Larky2k** [comment]
Your the only two with this issue. Which means it's hardware related. Have your tried running IR, TrackAPI in a clean no other mod instance

**Comment by TrainLord** [comment]
well it worked fine on my old Lenovo Thinkpad Yoga 270

**Comment by TrainLord** [comment]
but now im using an HP laptop with windows 10

**Comment by TrainLord** [comment]
also im using immersive engineering

**Comment by Larky2k** [comment]
just do a clean install of IR, TrackAPI and forge and nothing else and see if the problem persists

**Comment by TrainLord** [comment]
what does that mean?

**Comment by TrainLord** [comment]
like redownload it ive done that

**Comment by TrainLord** [comment]
about a few days ago

**Comment by Larky2k** [comment]
just make an instance that is just IR and TrackAPI running latest forge

**Comment by Larky2k** [comment]
at no point did i say redownload

**Comment by TrainLord** [comment]
oh ok

**Comment by TrainLord** [comment]
thanks i will try that

**Comment by TrainLord** [comment]
not working still

**Comment by TrainLord** [comment]
the mod is broken for me

**Comment by Larky2k** [comment]
ok abit of hail mary, disable any program to your knowledge on the computer that has overlays (like monitoring software) and also disable your antivirus and run the instance that's just IR and TrackAPI

**Comment by cam72cam** [comment]
@Larky2k please stop.  That's bad advice

**Comment by Larky2k** [comment]
well iv had issue with IR with programs with overlays

**Comment by cam72cam** [comment]
@TrainLord can you upload the latest.log again now that you have disabled the resource pack?

**Comment by TrainLord** [comment]
[latest.log](https://github.com/cam72cam/ImmersiveRailroading/files/3581509/latest.log)

**Comment by TrainLord** [comment]
there

**Comment by cam72cam** [comment]
1): You updated to the latest unstable version of forge, not stable
2): I am seeing a odd exception that may be due to 1

**Comment by TrainLord** [comment]
oh
but i just got the latest forge version and it still wasnt working right

**Comment by TrainLord** [comment]
what is the name of the required forge for all the mods does it have to use immersive engineering?

**Comment by cam72cam** [comment]
Switch back to the latest *stable* version of forge and post the fml-client-latest.log.  It has more debug information.

**Comment by TrainLord** [comment]
ok

**Comment by WrongWeekend** [comment]
Immersive Engineering is not required to run Immersive Railroading. Track API is the only required mod.

The latest stable version of forge is listed under "Download Recommended". This version is 1.12.2 - 14.23.5.2768 to be exact.

**Comment by TrainLord** [comment]
i think i used that version and it wasnt working

**Comment by cam72cam** [comment]
I still need the fml-client-latest.log from that version

**Comment by TrainLord** [comment]
ok im getting in the game

**Comment by WrongWeekend** [comment]
Immersive Engineering was also recently updated, so having that mod present may have caused some new issues to appear.

**Comment by TrainLord** [comment]
[latest.log](https://github.com/cam72cam/ImmersiveRailroading/files/3581544/latest.log)

**Comment by cam72cam** [comment]
I keep seeing:
```
java.util.concurrent.ExecutionException: java.lang.IndexOutOfBoundsException: Index: 68, Size: 46
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_51]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_51]
	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185) [chd.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
Caused by: java.lang.IndexOutOfBoundsException: Index: 68, Size: 46
	at java.util.ArrayList.rangeCheck(ArrayList.java:653) ~[?:1.8.0_51]
	at java.util.ArrayList.get(ArrayList.java:429) ~[?:1.8.0_51]
	at net.minecraft.inventory.Container.func_184996_a(Container.java:239) ~[afr.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147351_a(NetHandlerPlayServer.java:1160) ~[pa.class:?]
	at net.minecraft.network.play.client.CPacketClickWindow.func_148833_a(CPacketClickWindow.java:38) ~[lf.class:?]
	at net.minecraft.network.play.client.CPacketClickWindow.func_148833_a(CPacketClickWindow.java:12) ~[lf.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_51]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_51]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	... 5 more
```

in your logs.  Try removing Immersive Engineering as @WrongWeekend suggested

**Comment by TrainLord** [comment]
ok

**Comment by TrainLord** [comment]
hopefully that will work

**Comment by TrainLord** [comment]
didn't help

**Comment by TrainLord** [comment]
i guess i cant play the mod

**Comment by TrainLord** [comment]
it used to work fine before

**Comment by WrongWeekend** [comment]
Did you clear your config folder?

**Comment by TrainLord** [comment]
hang on

**Comment by TrainLord** [comment]
still not working and i cleard the config folder

**Comment by cam72cam** [comment]
You still never sent your fml client log.

**Comment by TrainLord** [comment]
oh

**Comment by TrainLord** [comment]
where do i find that?

**Comment by TrainLord** [comment]
[New Compressed (zipped) Folder.zip](https://github.com/cam72cam/ImmersiveRailroading/files/3581572/New.Compressed.zipped.Folder.zip)
its in there

**Comment by TrainLord** [comment]
i hope thats the right log file in the zip folder

**Comment by cam72cam** [comment]
that is an xml file, I am looking for a log file

**Comment by TrainLord** [comment]
oh ok

**Comment by TrainLord** [comment]
[2019-09-02-1.log.gz](https://github.com/cam72cam/ImmersiveRailroading/files/3581576/2019-09-02-1.log.gz)

**Comment by TrainLord** [comment]
is this it

**Comment by TrainLord** [comment]
im not good with finding the fml-client-latest.log

**Comment by cam72cam** [comment]
how about a debug.log?

**Comment by TrainLord** [comment]
ok here
[debug-1.log.gz](https://github.com/cam72cam/ImmersiveRailroading/files/3581581/debug-1.log.gz)
[debug-2.log.gz](https://github.com/cam72cam/ImmersiveRailroading/files/3581582/debug-2.log.gz)
[debug-3.log.gz](https://github.com/cam72cam/ImmersiveRailroading/files/3581583/debug-3.log.gz)
[debug-4.log.gz](https://github.com/cam72cam/ImmersiveRailroading/files/3581584/debug-4.log.gz)
[debug-5.log.gz](https://github.com/cam72cam/ImmersiveRailroading/files/3581585/debug-5.log.gz)

**Comment by cam72cam** [comment]
I just need the single .log, not the .gz versions

**Comment by TrainLord** [comment]
oh i cant find that in my log file

**Comment by TrainLord** [comment]
[debug.log](https://github.com/cam72cam/ImmersiveRailroading/files/3581589/debug.log)

**Comment by TrainLord** [comment]
oh this is it nevermind

**Comment by WrongWeekend** [comment]
You are using an out of date version of IR.

Download the latest version of IR here:
https://www.curseforge.com/minecraft/mc-mods/immersive-railroading/files/2706327

**Comment by TrainLord** [comment]
i know i was testing to see if using an out of date would help but i was wrong

**Comment by cam72cam** [comment]
@TrainLord I found your problem.  Updating IR is recommended but not nessesary to fix your problem:
```
[18:25:05] [main/INFO] [FML]: FML has found a non-mod file forge-1.12.2-14.23.5.2768.jar in your mods directory. It will now be injected into your classpath. This could severe stability issues, it should be removed if possible.
```

Remove the forge jar from your mods folder and try again

**Comment by TrainLord** [comment]
oh

**Comment by TrainLord** [comment]
recommended or latest forge?

**Comment by cam72cam** [comment]
recommended

**Comment by TrainLord** [comment]
ok

**Comment by TrainLord** [comment]
hopefully that will help

**Comment by cam72cam** [comment]
removing the forge jar from the mods folder will fix your issue

**Comment by TrainLord** [comment]
lets hope because i really like ur mod

**Comment by TrainLord** [comment]
nope still not working

**Comment by km00700** [comment]
could you send the new debug log?

**Comment by TrainLord** [comment]
[debug.log](https://github.com/cam72cam/ImmersiveRailroading/files/3581628/debug.log)

**Comment by cam72cam** [comment]
```
FML has found a non-mod file forge-1.12.2-14.23.5.2768-installer.jar in your mods directory
```

Remove that file from your mods directory

**Comment by TrainLord** [comment]
mod folder right

**Comment by TrainLord** [comment]
just removed forge

**Comment by cam72cam** [comment]
there should be no file in your mods folder with "forge" in the name.

**Comment by TrainLord** [comment]
it was the forge installer right

**Comment by cam72cam** [comment]
yes

**Comment by TrainLord** [comment]
i deleted that one

**Comment by TrainLord** [comment]
what do i do now

**Comment by WrongWeekend** [comment]
With forge removed from your mods folder, restart Minecraft and try again.

**Comment by TrainLord** [comment]
oh

**Comment by TrainLord** [comment]
so open 1.12.2 then redownload forge

**Comment by km00700** [comment]
you don't need to redownload anything.

**Comment by km00700** [comment]
Forge is still installed without that file in your mods folder.

**Comment by TrainLord** [comment]
oh

**Comment by WrongWeekend** [comment]
Redownloading forge is not necessary.

Your mods folder should have *only* these two files when you start Minecraft:

https://www.curseforge.com/minecraft/mc-mods/immersive-railroading/files/2706327

https://www.curseforge.com/minecraft/mc-mods/track-api/files/2535626

**Comment by TrainLord** [comment]
ok

**Comment by TrainLord** [comment]
it better work

**Comment by TrainLord** [comment]
not working still

**Comment by km00700** [comment]
send the log once more, please.

**Comment by TrainLord** [comment]
[debug.log](https://github.com/cam72cam/ImmersiveRailroading/files/3581670/debug.log)
[latest.log](https://github.com/cam72cam/ImmersiveRailroading/files/3581671/latest.log)

**Comment by WrongWeekend** [comment]
Try removing Immersive Engineering from the mods folder (Do *not* put it back in). Also delete your config and resourcepacks folders. Then try running Minecraft again.

**Comment by TrainLord** [comment]
ok

**Comment by Endalion** [comment]
If that does not work, create a completely new clean slate minecraft instance, install forge 2768 and **only** put IR and trackAPI in it, then run it.

**Comment by TrainLord** [comment]
ok

**Comment by TrainLord** [comment]
so do i delete minecraft entirely and redownload it

**Comment by TrainLord** [comment]
because it wasnt working

**Comment by TrainLord** [comment]
redownloading minecraft

**Comment by WrongWeekend** [comment]
Can you post latest.log and debug.log?

**Comment by TrainLord** [comment]
i already deleted minecraft i have to redownload the entire game

**Comment by TrainLord** [comment]
now i cant get minecraft back

**Comment by TrainLord** [comment]
nvm

**Comment by TrainLord** [comment]
mod is still broken

**Comment by TrainLord** [comment]
it still wont take the feul

**Comment by WrongWeekend** [comment]
Can you post latest.log and debug.log?

**Comment by TrainLord** [comment]
[debug.log](https://github.com/cam72cam/ImmersiveRailroading/files/3581742/debug.log)
[latest.log](https://github.com/cam72cam/ImmersiveRailroading/files/3581743/latest.log)

**Comment by TrainLord** [comment]
my game is broken
