### ISSUE TITLE
Bogies not following correct track

### ISSUE THREAD

**Issue by Dickovski** [cam72cam/ImmersiveRailroading#638]

**Comment by Larky2k** [comment]
how close are the two tracks?

**Comment by Dickovski** [comment]
****
A wonderful mod, so much better than the vanilla rail system but does still have some issues.
I've set up a loop to reverse trains (don't like the turntable, it's much too big).  The attached image shows the return, two parallel loops which come back onto the twin tracks via two turnouts.  Front bogies of locomotives on the nearest curve follow the left hand track, the rear bogies follow the right hand track, partially demolishing the platforms seen in the distance.
![Bogies not following correct track](https://user-images.githubusercontent.com/20523644/63687455-9e1e9080-c7fc-11e9-81eb-c2a38d75a228.jpg)

**Comment by Larky2k** [comment]
your track is to close
