### ISSUE TITLE
Server download error on Twitch app

### ISSUE THREAD

**Issue by aurimilky** [cam72cam/ImmersiveRailroading#649]
I am trying to download your mod pack, Exploration rails - Immersive Railroading Server and I keep getting the following error each time I try downloading on Twitch app in windows 10 64 bit.

"Timeout attempting to download: https://edge.forgecdn.net/files/2740/630/American Steam Locomotive Pack.zip"

9/12/19 Exploration Rails - 2.0.1 Beta

**Comment by WrongWeekend** [comment]
Immersive Railroading currently does not have an official modpack. You will have to submit the issue to that modpack's creator.
