### ISSUE TITLE
Use gamemode to determine infinite liquid config

### ISSUE THREAD

**Issue by cam72cam** [cam72cam/ImmersiveRailroading#77]
@DonBruce64's suggestion

**Comment by beilber** [comment]
To expand on this, I'd like to throw in the idea of having modules for the cars where applicabble.  I would see this as being a creative module you can attach to a tank, rolling stock.  Aside from having some potentially great options by having "upgrade modules", it make troubleshooting/testing much easier since you can simply use the module in SMP rather than other complexities.  Thoughts?

**Comment by DonBruce64** [comment]
Can you define what you mean by module?  I'm a hair confused about that, as the liquid bit is a GUI thing.  Do you mean the ability to have liquids in non-steam locomotives?  If so, I fail to see how it would be SMP-specific.

**Comment by beilber** [comment]
Sure, my thoughts are having inventory slots that you can apply essentially upgrade modules to the car in question.  So for this example of having a creative liquid tanker you would could a creative upgrade module in one of these upgrade slots to enable it specificlly for that tanker.  Using the gamemode in single player is not very complex, but how does that translate to multiplayer?  I can't speak to it myself but it sounds like it would be quite complicated to implement.

Hope that clears up my thoughts on the matter.

Down the road I can see modules being a great option to do the following, specific to tanker cars:

- Valve upgrade module - increase transfer rates
- Reinforcement module - allow storage of lava, or other molten forge materials
- Gas module - allow storage of gasses

**Comment by DonBruce64** [comment]
Single-Player is essentially Multi-Player just with the server and client bundled together and the user a permanent OP.  In general, it's better to develop for MP and then do some proxy checks and isRemote calls to ensure dedicated server (MP) code doesn't get called on the integrated server (SP).

As to the module bits, I leave that up to Cam.  Perhaps he'd want to make new stock, or perhaps he'd want to do modules.  Not sure.  I do want to say, Cam, that it might be easier to not use a GUI and simply make the modules a permanent upgrade.  GUI syncing can be flaky, and I find it easier to simply check fluid transfer in the loader/unloader block code server-side and send a packet to the client.  Though you could probably get away with no packets as long as you aren't doing rendering on the tank based on levels.

**Comment by cam72cam** [comment]
Won't fix
