### ISSUE TITLE
Breaking track overloads the sound system.

### ISSUE THREAD

**Issue by DonBruce64** [cam72cam/ImmersiveRailroading#81]
When you break track, it spawns a block break sound for every block in the track.  Minecraft has a maximum of 20 sounds it can play at once.  Therefore, when you break a track with 20 or more blocks all other sounds cut out as MC tries to shuffle it's sound.  This results in train explosions being mute if they occur on large track segments.

**Comment by cam72cam** [comment]
This was fixed by hacking at the sound system
