### ISSUE TITLE
Sound System

### ISSUE THREAD

**Issue by cam72cam** [cam72cam/ImmersiveRailroading#9]
TODO

**Comment by trainman264** [comment]
Working on it already

**Comment by trainman264** [comment]
Got the sounds

**Comment by DonBruce64** [comment]
Pro-tip.  If you're going to spawn piston sounds for engines, don't do it in the main game loop.  While that's the correct way, it spazzes out if you have fast queues.  RoW has this issue as there's only 1/20 of a second to catch wheels being in the correct piston for a piston chuff.

A more robust way is to access the SoundManager in the rendering call and spawn sounds there.  That way you can spawn sounds on partial ticks and make things more accurate.  Also you reduce network lag as you're putting sounds directly into the sound pipeline and not passing sound events from the server to all clients.
