### ISSUE TITLE
Applying more brakes than throttle results in train traveling backwards.

### ISSUE THREAD

**Issue by DonBruce64** [cam72cam/ImmersiveRailroading#90]
Hooked up a K4 and a Peppercorn to a Big Boy.  K4 was in slight forwards, causing the A1 and BB to follow.  Applied brakes on the A1 and the train slowed down, applied brakes on the BB and the train started going in the other direction.

**Comment by DonBruce64** [comment]
Looks like it might be related to thrust rather than braking as I can cause engines to go in the wrong direction if there's a larger thrust source pointing the other direction.
![image](https://user-images.githubusercontent.com/15241611/30526076-9bef8298-9bd9-11e7-9381-a64c48738879.png)

**Comment by cam72cam** [comment]
Fixed by brake vs throttle scaling
